numixproject/numix-icon-theme

Numix/128x128/places/folder-gdrive.svg, Numix/16x16/places/folder-gdrive.svg, Numix/22x22/places/folder-gdrive.svg, Numix/24x24/places/folder-gdrive.svg, Numix/256x256/places/folder-gdrive.svg, Numix/32x32/places/folder-gdrive.svg, Numix/48x48/places/folder-gdrive.svg, Numix/64x64/places/folder-gdrive.svg
Since we are hopefully getting an official goolge drive client for linux (fingers crossed: http://www.webupd8.org/2015/01/official-google-drive-linux-client.html), I thought it is necessary to have the proper places icons...
=> Adds google drive folder icons

Numix/128x128/mimetypes/image-x-eps.svg, Numix/16x16/mimetypes/image-x-eps.svg, Numix/22x22/mimetypes/image-x-eps.svg, Numix/24x24/mimetypes/image-x-eps.svg, Numix/256x256/mimetypes/image-x-eps.svg, Numix/32x32/mimetypes/image-x-eps.svg, Numix/48x48/mimetypes/image-x-eps.svg, Numix/64x64/mimetypes/image-x-eps.svg
Added mimetypes (symlinks) for the EPS (Encapsulated PostScript) file format
=> Added mimetypes for the EPS file format

Numix/128x128/mimetypes/application-x-krita.svg, Numix/128x128/mimetypes/image-x-krita.svg, Numix/16x16/mimetypes/application-x-krita.svg, Numix/16x16/mimetypes/image-x-krita.svg, Numix/22x22/mimetypes/application-x-krita.svg, Numix/22x22/mimetypes/image-x-krita.svg, Numix/24x24/mimetypes/application-x-krita.svg, Numix/24x24/mimetypes/image-x-krita.svg, Numix/256x256/mimetypes/application-x-krita.svg, Numix/256x256/mimetypes/image-x-krita.svg, Numix/32x32/mimetypes/application-x-krita.svg, Numix/32x32/mimetypes/image-x-krita.svg, Numix/48x48/mimetypes/application-x-krita.svg, Numix/48x48/mimetypes/image-x-krita.svg, Numix/64x64/mimetypes/application-x-krita.svg, Numix/64x64/mimetypes/image-x-krita.svg
=> Krita KRT mimetype enhancement

Numix/128x128/mimetypes/audio-midi.svg, Numix/16x16/mimetypes/audio-midi.svg, Numix/22x22/mimetypes/audio-midi.svg, Numix/24x24/mimetypes/audio-midi.svg, Numix/256x256/mimetypes/audio-midi.svg, Numix/32x32/mimetypes/audio-midi.svg, Numix/48x48/mimetypes/audio-midi.svg, Numix/64x64/mimetypes/audio-midi.svg
Added MIDI mimetypes for all sizes
=> Added MIDI mimetypes

Numix/128x128/mimetypes/application-x-lyx.svg, Numix/128x128/mimetypes/text-x-lyx.svg, Numix/16x16/mimetypes/application-x-lyx.svg, Numix/16x16/mimetypes/text-x-lyx.svg, Numix/22x22/mimetypes/application-x-lyx.svg, Numix/22x22/mimetypes/text-x-lyx.svg, Numix/24x24/mimetypes/application-x-lyx.svg, Numix/24x24/mimetypes/text-x-lyx.svg, Numix/256x256/mimetypes/application-x-lyx.svg, Numix/256x256/mimetypes/text-x-lyx.svg, Numix/32x32/mimetypes/application-x-lyx.svg, Numix/32x32/mimetypes/text-x-lyx.svg, Numix/48x48/mimetypes/application-x-lyx.svg, Numix/48x48/mimetypes/text-x-lyx.svg, Numix/64x64/mimetypes/application-x-lyx.svg, Numix/64x64/mimetypes/text-x-lyx.svg
=> Added LYX mimetype

Numix/128x128/mimetypes/application-mbox.svg, Numix/128x128/mimetypes/message-rfc822.svg, Numix/16x16/mimetypes/application-mbox.svg, Numix/16x16/mimetypes/message-rfc822.svg, Numix/22x22/mimetypes/application-mbox.svg, Numix/22x22/mimetypes/message-rfc822.svg, Numix/24x24/mimetypes/application-mbox.svg, Numix/24x24/mimetypes/message-rfc822.svg, Numix/256x256/mimetypes/application-mbox.svg, Numix/256x256/mimetypes/message-rfc822.svg, Numix/32x32/mimetypes/application-mbox.svg, Numix/32x32/mimetypes/message-rfc822.svg, Numix/48x48/mimetypes/application-mbox.svg, Numix/48x48/mimetypes/message-rfc822.svg, Numix/64x64/mimetypes/application-mbox.svg, Numix/64x64/mimetypes/message-rfc822.svg
=> Added mbox mimetype

Numix/128x128/mimetypes/application-x-python-bytecode.svg, Numix/16x16/mimetypes/application-x-python-bytecode.svg, Numix/22x22/mimetypes/application-x-python-bytecode.svg, Numix/24x24/mimetypes/application-x-python-bytecode.svg, Numix/256x256/mimetypes/application-x-python-bytecode.svg, Numix/32x32/mimetypes/application-x-python-bytecode.svg, Numix/48x48/mimetypes/application-x-python-bytecode.svg, Numix/64x64/mimetypes/application-x-python-bytecode.svg
Added dedicated Python bytecode mimetype. Fixes #281
=> Added dedicated Python bytecode mimetype

Numix/48x48/mimetypes/application-pkix-cert.svg, Numix/48x48/mimetypes/application-x-x509-ca-cert.svg, Numix/48x48/mimetypes/application-x-x509-user-cert.svg
Create symlink for the following mimetypes:
```
application/x-x509-ca-cert
application/x-x509-user-cert
application/pkix-cert
```
For example:
=> add 3 certificate mimetype

Numix-Light/16x16/status/deluge-panel.svg, Numix-Light/24x24/status/deluge-panel.svg, Numix/22x22/status/deluge.svg
=> Deluge status icon corrections, fixes #334

Numix-Light/16x16/status/input-keyboard.svg, Numix-Light/22x22/status/input-keyboard.svg, Numix-Light/24x24/status/input-keyboard.svg, Numix/16x16/status/input-keyboard.svg, Numix/22x22/status/input-keyboard.svg, Numix/24x24/status/input-keyboard.svg
Same as #342, most probably the last one (this one is just a very minor inconsistency)
=> Fixes wrong scaling of input-keyboard.svg in 22 16 and 24

Numix/48x48/notifications/battery-caution-symbolic.svg, Numix/48x48/notifications/nm-device-wired.svg, Numix/48x48/notifications/nm-device-wireless.svg, Numix/48x48/notifications/nm-device-wwan.svg, Numix/48x48/notifications/notification-audio-volume-high.svg, Numix/48x48/notifications/notification-audio-volume-low.svg, Numix/48x48/notifications/notification-audio-volume-medium.svg, Numix/48x48/notifications/notification-audio-volume-muted.svg, Numix/48x48/notifications/notification-audio-volume-off.svg, Numix/48x48/notifications/notification-battery-000.svg, Numix/48x48/notifications/notification-battery-020.svg, Numix/48x48/notifications/notification-battery-empty.svg, Numix/48x48/notifications/notification-battery-low.svg, Numix/48x48/notifications/notification-display-brightness-full.svg, Numix/48x48/notifications/notification-display-brightness-high.svg, Numix/48x48/notifications/notification-display-brightness-low.svg, Numix/48x48/notifications/notification-display-brightness-medium.svg, Numix/48x48/notifications/notification-display-brightness-off.svg, Numix/48x48/notifications/notification-gsm-disconnected.svg, Numix/48x48/notifications/notification-network-ethernet-disconnected.svg, Numix/48x48/notifications/notification-network-wireless-disconnected.svg, Numix/index.theme
New pull request, everything was already said in #298 
One thing though: I used #ececec instead of #dcdcdc to be consistent with the new status icons
=> Adds notification icons

Numix-Light/16x16/status/nm-vpn-standalone-lock.svg, Numix-Light/24x24/status/nm-vpn-standalone-lock.svg, Numix/16x16/status/nm-vpn-standalone-lock.svg, Numix/24x24/status/nm-vpn-standalone-lock.svg
Same as #342 I think (and hope) that's the last one
=> Fixes wrong scaling of nm-vpn-standalone-lock.svg

Numix-Light/16x16/status/user-available-panel.svg, Numix-Light/16x16/status/user-away-panel.svg, Numix-Light/16x16/status/user-busy-panel.svg, Numix-Light/16x16/status/user-idle-panel.svg, Numix-Light/16x16/status/user-indeterminate-panel.svg, Numix-Light/16x16/status/user-invisible-panel.svg, Numix-Light/16x16/status/user-offline-panel.svg, Numix-Light/24x24/status/user-available-panel.svg, Numix-Light/24x24/status/user-away-panel.svg, Numix-Light/24x24/status/user-busy-panel.svg, Numix-Light/24x24/status/user-idle-panel.svg, Numix-Light/24x24/status/user-indeterminate-panel.svg, Numix-Light/24x24/status/user-invisible-panel.svg, Numix-Light/24x24/status/user-offline-panel.svg, Numix/16x16/status/user-available-panel.svg, Numix/16x16/status/user-away-panel.svg, Numix/16x16/status/user-busy-panel.svg, Numix/16x16/status/user-idle-panel.svg, Numix/16x16/status/user-indeterminate-panel.svg, Numix/16x16/status/user-invisible-panel.svg, Numix/16x16/status/user-offline-panel.svg, Numix/24x24/status/user-available-panel.svg, Numix/24x24/status/user-away-panel.svg, Numix/24x24/status/user-busy-panel.svg, Numix/24x24/status/user-idle-panel.svg, Numix/24x24/status/user-indeterminate-panel.svg, Numix/24x24/status/user-invisible-panel.svg, Numix/24x24/status/user-offline-panel.svg
Same problem as in #342 for user-*-panel.svg in both colors
=> Fixes wrong scaling of user-*-panel.svg in 16x16 and 24x24

Numix/128x128/mimetypes/application-mathematica.svg, Numix/16x16/mimetypes/application-mathematica.svg, Numix/22x22/mimetypes/application-mathematica.svg, Numix/24x24/mimetypes/application-mathematica.svg, Numix/256x256/mimetypes/application-mathematica.svg, Numix/32x32/mimetypes/application-mathematica.svg, Numix/48x48/mimetypes/application-mathematica.svg, Numix/64x64/mimetypes/application-mathematica.svg
Adds mimetypes for mathematica fixes #294 
Suggestions?
=> Adds mathematica mimetypes

Numix/22x22/status/pamac-tray-no-update.svg
Pretty self explanatory, something went wrong during redesign, all ok in numix-light
=> Fixes pamac-tray-no-update.svg in 22x22/status

Numix/128x128/mimetypes/application-pkix-cert.svg, Numix/128x128/mimetypes/application-x-x509-ca-cert.svg, Numix/128x128/mimetypes/application-x-x509-user-cert.svg, Numix/16x16/mimetypes/application-pkix-cert.svg, Numix/16x16/mimetypes/application-x-x509-ca-cert.svg, Numix/16x16/mimetypes/application-x-x509-user-cert.svg, Numix/22x22/mimetypes/application-pkix-cert.svg, Numix/22x22/mimetypes/application-x-x509-ca-cert.svg, Numix/22x22/mimetypes/application-x-x509-user-cert.svg, Numix/24x24/mimetypes/application-pkix-cert.svg, Numix/24x24/mimetypes/application-x-x509-ca-cert.svg, Numix/24x24/mimetypes/application-x-x509-user-cert.svg, Numix/256x256/mimetypes/application-pkix-cert.svg, Numix/256x256/mimetypes/application-x-x509-ca-cert.svg, Numix/256x256/mimetypes/application-x-x509-user-cert.svg, Numix/32x32/mimetypes/application-pkix-cert.svg, Numix/32x32/mimetypes/application-x-x509-ca-cert.svg, Numix/32x32/mimetypes/application-x-x509-user-cert.svg, Numix/64x64/mimetypes/application-pkix-cert.svg, Numix/64x64/mimetypes/application-x-x509-ca-cert.svg, Numix/64x64/mimetypes/application-x-x509-user-cert.svg
I made something wrong in the first moment. Now I've added all sizes #350
=> 3 certificates in all sizes

Numix-Light/16x16/status/indicator-messages.svg, Numix/16x16/status/indicator-messages.svg
This one was missed during redesign of status icons
=> Fixes wrong design of indicator-messages.svg in 16

Numix-Light/16x16/status/nm-adhoc.svg, Numix-Light/24x24/status/nm-adhoc.svg, Numix/16x16/status/nm-adhoc.svg, Numix/24x24/status/nm-adhoc.svg
Same as #342, scaling of nm-adhoc.svg in 16x16 and 24x24 is wrong
=> Fixes wrong scaling of nm-adhoc in 16 and 24

Numix/16x16/status/tray-new-im.svg, Numix/24x24/status/tray-new-im.svg
=> Fixes wrong scaling of tray-new-im.svg

Numix/16x16/status/battery-000.svg, Numix/22x22/status/battery-000.svg, Numix/24x24/status/battery-000.svg
Added brightness to battery-000.svg. Fixes https://github.com/numixproject/numix-icon-theme/issues/256.
=> Added brightness to battery-000.svg

Numix/128x128/mimetypes/text-x-lilypond.svg, Numix/16x16/mimetypes/text-x-lilypond.svg, Numix/22x22/mimetypes/text-x-lilypond.svg, Numix/24x24/mimetypes/text-x-lilypond.svg, Numix/256x256/mimetypes/text-x-lilypond.svg, Numix/32x32/mimetypes/text-x-lilypond.svg, Numix/48x48/mimetypes/text-x-lilypond.svg, Numix/64x64/mimetypes/text-x-lilypond.svg
=> Added Lilypond mimetype

Numix/128x128/mimetypes/application-x-subrip.svg, Numix/16x16/mimetypes/application-x-subrip.svg, Numix/22x22/mimetypes/application-x-subrip.svg, Numix/24x24/mimetypes/application-x-subrip.svg, Numix/256x256/mimetypes/application-x-subrip.svg, Numix/32x32/mimetypes/application-x-subrip.svg, Numix/48x48/mimetypes/application-x-subrip.svg, Numix/64x64/mimetypes/application-x-subrip.svg
#362 
For some reason the github preview doesn't show the properly icon.
@palob Do you know if I need to modify something else?
=> Fixes #362

Numix/128x128/mimetypes/audio-x-midi.svg, Numix/16x16/mimetypes/audio-x-midi.svg, Numix/22x22/mimetypes/audio-x-midi.svg, Numix/24x24/mimetypes/audio-x-midi.svg, Numix/256x256/mimetypes/audio-x-midi.svg, Numix/32x32/mimetypes/audio-x-midi.svg, Numix/48x48/mimetypes/audio-x-midi.svg, Numix/64x64/mimetypes/audio-x-midi.svg
=> Added missing MIDI mimetype symlink

Numix/128x128/mimetypes/application-json.svg, Numix/16x16/mimetypes/application-json.svg, Numix/22x22/mimetypes/application-json.svg, Numix/24x24/mimetypes/application-json.svg, Numix/256x256/mimetypes/application-json.svg, Numix/32x32/mimetypes/application-json.svg, Numix/48x48/mimetypes/application-json.svg, Numix/64x64/mimetypes/application-json.svg
Added JSON mimetype. Fixes #336
=> Added JSON mimetype

Numix/128x128/mimetypes/text-x-fortran.svg, Numix/16x16/mimetypes/text-x-fortran.svg, Numix/22x22/mimetypes/text-x-fortran.svg, Numix/24x24/mimetypes/text-x-fortran.svg, Numix/256x256/mimetypes/text-x-fortran.svg, Numix/32x32/mimetypes/text-x-fortran.svg, Numix/48x48/mimetypes/text-x-fortran.svg, Numix/64x64/mimetypes/text-x-fortran.svg
=> Added Fortran mimetype

Numix/128x128/mimetypes/message-news.svg, Numix/128x128/mimetypes/message-x-gnu-rmail.svg, Numix/16x16/mimetypes/message-news.svg, Numix/16x16/mimetypes/message-x-gnu-rmail.svg, Numix/22x22/mimetypes/message-news.svg, Numix/22x22/mimetypes/message-x-gnu-rmail.svg, Numix/24x24/mimetypes/message-news.svg, Numix/24x24/mimetypes/message-x-gnu-rmail.svg, Numix/256x256/mimetypes/message-news.svg, Numix/256x256/mimetypes/message-x-gnu-rmail.svg, Numix/32x32/mimetypes/message-news.svg, Numix/32x32/mimetypes/message-x-gnu-rmail.svg, Numix/48x48/mimetypes/message-news.svg, Numix/48x48/mimetypes/message-x-gnu-rmail.svg, Numix/64x64/mimetypes/message-news.svg, Numix/64x64/mimetypes/message-x-gnu-rmail.svg
Links to *application-mbox.svg*
=> Added mimetypes for Newsgroup and Rmail messages (symlinks)

Numix/128x128/mimetypes/text-x-cmake.svg, Numix/16x16/mimetypes/text-x-cmake.svg, Numix/22x22/mimetypes/text-x-cmake.svg, Numix/24x24/mimetypes/text-x-cmake.svg, Numix/256x256/mimetypes/text-x-cmake.svg, Numix/32x32/mimetypes/text-x-cmake.svg, Numix/48x48/mimetypes/text-x-cmake.svg, Numix/64x64/mimetypes/text-x-cmake.svg
=> Added symlinks for CMake mimetype

Numix/128x128/mimetypes/application-x-sami.svg, Numix/128x128/mimetypes/text-x-microdvd.svg, Numix/16x16/mimetypes/application-x-sami.svg, Numix/16x16/mimetypes/text-x-microdvd.svg, Numix/22x22/mimetypes/application-x-sami.svg, Numix/22x22/mimetypes/text-x-microdvd.svg, Numix/24x24/mimetypes/application-x-sami.svg, Numix/24x24/mimetypes/text-x-microdvd.svg, Numix/256x256/mimetypes/application-x-sami.svg, Numix/256x256/mimetypes/text-x-microdvd.svg, Numix/32x32/mimetypes/application-x-sami.svg, Numix/32x32/mimetypes/text-x-microdvd.svg, Numix/48x48/mimetypes/application-x-sami.svg, Numix/48x48/mimetypes/text-x-microdvd.svg, Numix/64x64/mimetypes/application-x-sami.svg, Numix/64x64/mimetypes/text-x-microdvd.svg
Mimetypes:
- MicroDVD subtitles (text/x-microdvd)
- SAMI subtitles (application/x-sami)
=> add two subtitles mimetypes

Numix/128x128/mimetypes/text-x-lua.svg, Numix/16x16/mimetypes/text-x-lua.svg, Numix/22x22/mimetypes/text-x-lua.svg, Numix/24x24/mimetypes/text-x-lua.svg, Numix/256x256/mimetypes/text-x-lua.svg, Numix/32x32/mimetypes/text-x-lua.svg, Numix/48x48/mimetypes/text-x-lua.svg, Numix/64x64/mimetypes/text-x-lua.svg
Replaced the hashbang icon (symlink to shell script mime) with:
=> Lua mimetype enhancement

Numix-Light/16x16/status/variety-indicator.svg, Numix-Light/22x22/status/variety-indicator.svg, Numix-Light/24x24/status/variety-indicator.svg, Numix/16x16/status/variety-indicator.svg, Numix/22x22/status/variety-indicator.svg, Numix/24x24/status/variety-indicator.svg
variety-indicator in all sizes
=> Adds variety-indicator, fixes #375

Numix/128x128/mimetypes/text-x-dsrc.svg, Numix/16x16/mimetypes/text-x-dsrc.svg, Numix/22x22/mimetypes/text-x-dsrc.svg, Numix/24x24/mimetypes/text-x-dsrc.svg, Numix/256x256/mimetypes/text-x-dsrc.svg, Numix/32x32/mimetypes/text-x-dsrc.svg, Numix/48x48/mimetypes/text-x-dsrc.svg, Numix/64x64/mimetypes/text-x-dsrc.svg
=> Added mimetype for D language source files

Numix-Light/16x16/status/grive-app-ind-con-1.svg, Numix-Light/16x16/status/grive-app-ind-con-2.svg, Numix-Light/16x16/status/grive-app-ind-con-3.svg, Numix-Light/16x16/status/grive-app-ind-sleep.svg, Numix-Light/16x16/status/grive-app-ind.svg, Numix-Light/22x22/status/grive-app-ind-con-1.svg, Numix-Light/22x22/status/grive-app-ind-con-2.svg, Numix-Light/22x22/status/grive-app-ind-con-3.svg, Numix-Light/22x22/status/grive-app-ind-sleep.svg, Numix-Light/22x22/status/grive-app-ind.svg, Numix-Light/24x24/status/grive-app-ind-con-1.svg, Numix-Light/24x24/status/grive-app-ind-con-2.svg, Numix-Light/24x24/status/grive-app-ind-con-3.svg, Numix-Light/24x24/status/grive-app-ind-sleep.svg, Numix-Light/24x24/status/grive-app-ind.svg, Numix/16x16/status/grive-app-ind-con-1.svg, Numix/16x16/status/grive-app-ind-con-2.svg, Numix/16x16/status/grive-app-ind-con-3.svg, Numix/16x16/status/grive-app-ind-sleep.svg, Numix/16x16/status/grive-app-ind.svg, Numix/22x22/status/grive-app-ind-con-1.svg, Numix/22x22/status/grive-app-ind-con-2.svg, Numix/22x22/status/grive-app-ind-con-3.svg, Numix/22x22/status/grive-app-ind-sleep.svg, Numix/22x22/status/grive-app-ind.svg, Numix/24x24/status/grive-app-ind-con-1.svg, Numix/24x24/status/grive-app-ind-con-2.svg, Numix/24x24/status/grive-app-ind-con-3.svg, Numix/24x24/status/grive-app-ind-sleep.svg, Numix/24x24/status/grive-app-ind.svg
Status icons for google-drive-sync client grive (May also be used if an official google drive client happens :)
http://www.webupd8.org/2012/05/grive-open-source-google-drive-client.html
=> Adds status icon for grive indicator

Numix-Light/16x16/status/todo-indicator.svg, Numix-Light/22x22/status/todo-indicator.svg, Numix-Light/24x24/status/todo-indicator.svg, Numix/16x16/status/todo-indicator.svg, Numix/22x22/status/todo-indicator.svg, Numix/24x24/status/todo-indicator.svg
=> Adds status icons for todo-indicator

Numix/128x128/mimetypes/application-rdata.svg, Numix/128x128/mimetypes/text-r.svg, Numix/16x16/mimetypes/application-rdata.svg, Numix/16x16/mimetypes/text-r.svg, Numix/22x22/mimetypes/application-rdata.svg, Numix/22x22/mimetypes/text-r.svg, Numix/24x24/mimetypes/application-rdata.svg, Numix/24x24/mimetypes/text-r.svg, Numix/256x256/mimetypes/application-rdata.svg, Numix/256x256/mimetypes/text-r.svg, Numix/32x32/mimetypes/application-rdata.svg, Numix/32x32/mimetypes/text-r.svg, Numix/48x48/mimetypes/application-rdata.svg, Numix/48x48/mimetypes/text-r.svg, Numix/64x64/mimetypes/application-rdata.svg, Numix/64x64/mimetypes/text-r.svg
It appears there were still missing some.
=> Added missing symlinks for the R mimetype

Numix-Light/16x16/status/tomboy-panel.svg, Numix-Light/22x22/status/tomboy-panel.svg, Numix-Light/24x24/status/tomboy-panel.svg, Numix/16x16/status/tomboy-panel.svg, Numix/22x22/status/tomboy-panel.svg, Numix/24x24/status/tomboy-panel.svg
=> Adds tomboy status icons

Numix/128x128/devices/audio-headphones.svg, Numix/16x16/devices/audio-headphones.svg, Numix/22x22/devices/audio-headphones.svg, Numix/24x24/devices/audio-headphones.svg, Numix/256x256/devices/audio-headphones.svg, Numix/32x32/devices/audio-headphones.svg, Numix/48x48/devices/audio-headphones.svg, Numix/64x64/devices/audio-headphones.svg
=> Adds missing symlink fixes #261

Numix-Light/16x16/status/blueman-active.svg, Numix-Light/16x16/status/blueman-disabled.svg, Numix-Light/22x22/status/blueman-active.svg, Numix-Light/22x22/status/blueman-disabled.svg, Numix-Light/24x24/status/blueman-active.svg, Numix-Light/24x24/status/blueman-disabled.svg, Numix/16x16/status/blueman-active.svg, Numix/16x16/status/blueman-disabled.svg, Numix/22x22/status/blueman-active.svg, Numix/22x22/status/blueman-disabled.svg, Numix/24x24/status/blueman-active.svg, Numix/24x24/status/blueman-disabled.svg
=> Add symlinks for blueman status icons

Numix-Light/16x16/status/clipman.svg, Numix-Light/22x22/status/clipman.svg, Numix-Light/24x24/status/clipman.svg, Numix/16x16/status/clipman.svg, Numix/22x22/status/clipman.svg, Numix/24x24/status/clipman.svg
=> Adds clipman status icons fixes #151

Numix/128x128/status/dialog-error.svg, Numix/16x16/status/dialog-error.svg, Numix/22x22/status/dialog-error.svg, Numix/24x24/status/dialog-error.svg, Numix/256x256/status/dialog-error.svg, Numix/32x32/status/dialog-error.svg, Numix/48x48/status/dialog-error.svg, Numix/64x64/status/dialog-error.svg
=> dialog-error.svg align

Numix/128x128/categories/applications-fonts.svg, Numix/16x16/categories/applications-fonts.svg, Numix/22x22/categories/applications-fonts.svg, Numix/24x24/categories/applications-fonts.svg, Numix/256x256/categories/applications-fonts.svg, Numix/32x32/categories/applications-fonts.svg, Numix/48x48/categories/applications-fonts.svg, Numix/64x64/categories/applications-fonts.svg
Adds applications-fonts to all sizes. I took the design from two years ago from a commit that still had it :)
https://github.com/numixproject/numix-icon-theme/blob/eb559cecc6b759a45be2d21c89b402a0ee3b3a31/Numix/categories/48/applications-fonts.svg
=> Adds applications-fonts for all sizes fixes #237

Numix-Light/16x16/status/blueman.svg, Numix-Light/22x22/status/blueman.svg, Numix-Light/24x24/status/blueman.svg, Numix/16x16/status/blueman.svg, Numix/22x22/status/blueman.svg, Numix/24x24/status/blueman.svg
I forgot one in my pull request a few weeks ago.
=> Add missing blueman status icon

Numix-Light/16x16/status/battery-caution.svg, Numix-Light/16x16/status/battery-low.svg, Numix-Light/22x22/status/battery-caution.svg, Numix-Light/22x22/status/battery-low.svg, Numix-Light/24x24/status/battery-caution.svg, Numix-Light/24x24/status/battery-low.svg, Numix/16x16/status/battery-caution.svg, Numix/16x16/status/battery-low.svg, Numix/22x22/status/battery-caution.svg, Numix/22x22/status/battery-low.svg, Numix/24x24/status/battery-caution.svg, Numix/24x24/status/battery-low.svg
In continuation of #206 and #452 and @dirtydancing  asked me to do it, this fixes #236
=> Removes unnecessary battery symlinks from 16 22 and 24

Numix/48x48/devices/network-vpn.svg
This one slipped through in my previous pull-request
=> Wrong size of network-vpn in 48

Numix/16x16/devices/nm-device-wireless.svg, Numix/22x22/devices/nm-device-wireless.svg, Numix/24x24/devices/nm-device-wireless.svg, Numix/32x32/devices/nm-device-wireless.svg
Enhances nm-device-wireless.svg in devices. Cf. #472
=> Enhances nm-device-wireless. Fixes #472

Numix/48x48/notifications/notification-network-ethernet-connected.svg, Numix/48x48/notifications/notification-network-ethernet-disconnected.svg, Numix/scalable/status/network-wired-symbolic.svg
Since we have now new and pretty devices icons the notifications icon for ethernet needs to be made consistent. Fixes #473 (kind of :)
=> Fixes #473

Numix/128x128/actions/geany-build.svg, Numix/128x128/actions/geany-close-all, Numix/128x128/actions/geany-save-all.svg, Numix/16x16/actions/geany-build.svg, Numix/16x16/actions/geany-close-all, Numix/16x16/actions/geany-save-all.svg, Numix/22x22/actions/geany-build.svg, Numix/22x22/actions/geany-close-all, Numix/22x22/actions/geany-save-all.svg, Numix/24x24/actions/geany-build.svg, Numix/24x24/actions/geany-close-all, Numix/24x24/actions/geany-save-all.svg, Numix/256x256/actions/geany-build.svg, Numix/256x256/actions/geany-close-all, Numix/256x256/actions/geany-save-all.svg, Numix/32x32/actions/geany-build.svg, Numix/32x32/actions/geany-close-all, Numix/32x32/actions/geany-save-all.svg, Numix/48x48/actions/geany-build.svg, Numix/48x48/actions/geany-close-all, Numix/48x48/actions/geany-save-all.svg, Numix/64x64/actions/geany-build.svg, Numix/64x64/actions/geany-close-all, Numix/64x64/actions/geany-save-all.svg
Adds geany (great editor btw) action icons. Fixes the non gtk icons from #284. Everything aligned to grid as good as possible.
I don't want the bounty so you can but it on something else (preferably a base issue :)
=> Adds geany action icons fixes #284

Numix/128x128/status/dialog-password.svg, Numix/16x16/status/dialog-password.svg, Numix/22x22/status/dialog-password.svg, Numix/24x24/status/dialog-password.svg, Numix/256x256/status/dialog-password.svg, Numix/32x32/status/dialog-password.svg, Numix/48x48/status/dialog-password.svg, Numix/64x64/status/dialog-password.svg
=> Fixes #285

Numix-Light/16x16/status/hipchat.svg, Numix-Light/22x22/status/hipchat.svg, Numix-Light/24x24/status/hipchat.svg, Numix/16x16/status/hipchat-attention.svg, Numix/16x16/status/hipchat.svg, Numix/22x22/status/hipchat-attention.svg, Numix/22x22/status/hipchat.svg, Numix/24x24/status/hipchat-attention.svg, Numix/24x24/status/hipchat.svg
=> Adds hipchat status icons, fixes #370

Numix-Light/16x16/status/clipit-trayicon.svg, Numix-Light/22x22/status/clipit-trayicon.svg, Numix-Light/24x24/status/clipit-trayicon.svg, Numix/16x16/status/clipit-trayicon.svg, Numix/22x22/status/clipit-trayicon.svg, Numix/24x24/status/clipit-trayicon.svg
=> Adds clipit trayicons (symlinks)

Numix/128x128/actions/gtk-undelete.svg, Numix/16x16/actions/gtk-undelete.svg, Numix/22x22/actions/gtk-undelete.svg, Numix/24x24/actions/gtk-undelete.svg, Numix/256x256/actions/gtk-undelete.svg, Numix/32x32/actions/gtk-undelete.svg, Numix/48x48/actions/gtk-undelete.svg, Numix/64x64/actions/gtk-undelete.svg
One icon from the gtk list at #315
=> Adds gtk-undelete to actions

Numix-Light/16x16/status/indicator-netspeed-idle-d.svg, Numix-Light/16x16/status/indicator-netspeed-receive-d.svg, Numix-Light/16x16/status/indicator-netspeed-transmit-d.svg, Numix-Light/16x16/status/indicator-netspeed-transmit-receive-d.svg, Numix-Light/22x22/status/indicator-netspeed-idle-d.svg, Numix-Light/22x22/status/indicator-netspeed-receive-d.svg, Numix-Light/22x22/status/indicator-netspeed-transmit-d.svg, Numix-Light/22x22/status/indicator-netspeed-transmit-receive-d.svg, Numix-Light/24x24/status/indicator-netspeed-idle-d.svg, Numix-Light/24x24/status/indicator-netspeed-receive-d.svg, Numix-Light/24x24/status/indicator-netspeed-transmit-d.svg, Numix-Light/24x24/status/indicator-netspeed-transmit-receive-d.svg, Numix/16x16/status/indicator-netspeed-idle-l.svg, Numix/16x16/status/indicator-netspeed-receive-l.svg, Numix/16x16/status/indicator-netspeed-transmit-l.svg, Numix/16x16/status/indicator-netspeed-transmit-receive-l.svg, Numix/22x22/status/indicator-netspeed-idle-l.svg, Numix/22x22/status/indicator-netspeed-receive-l.svg, Numix/22x22/status/indicator-netspeed-transmit-l.svg, Numix/22x22/status/indicator-netspeed-transmit-receive-l.svg, Numix/24x24/status/indicator-netspeed-idle-l.svg, Numix/24x24/status/indicator-netspeed-receive-l.svg, Numix/24x24/status/indicator-netspeed-transmit-l.svg, Numix/24x24/status/indicator-netspeed-transmit-receive-l.svg
This will fix #505 
but there's one issue , the original ``` network-idle.svg``` and the ``` network-transmit-receive.svg``` are the same,  which must not be the case
I hope someone else will create a pull request to fix this
=> Fixes Netspeed indicator

Numix-Light/16x16/status/zim-panel.svg, Numix-Light/22x22/status/zim-panel.svg, Numix-Light/24x24/status/zim-panel.svg, Numix/16x16/status/zim-panel.svg, Numix/22x22/status/zim-panel.svg, Numix/24x24/status/zim-panel.svg
=> adds zim-wiki status indicators, fixes #414

Numix/128x128/actions/gtk-color-picker.svg, Numix/16x16/actions/gtk-color-picker.svg, Numix/22x22/actions/gtk-color-picker.svg, Numix/24x24/actions/gtk-color-picker.svg, Numix/256x256/actions/gtk-color-picker.svg, Numix/32x32/actions/gtk-color-picker.svg, Numix/48x48/actions/gtk-color-picker.svg, Numix/64x64/actions/gtk-color-picker.svg
=> Adds gtk-color-picker

Numix/128x128/actions/gtk-select-color.svg, Numix/16x16/actions/gtk-select-color.svg, Numix/22x22/actions/gtk-select-color.svg, Numix/24x24/actions/gtk-select-color.svg, Numix/256x256/actions/gtk-select-color.svg, Numix/32x32/actions/gtk-select-color.svg, Numix/48x48/actions/gtk-select-color.svg, Numix/64x64/actions/gtk-select-color.svg
One icon slipped through in one of my previous PRs
=> Inconsistency in gtk-color-chooser

Numix/128x128/actions/gtk-select-color.svg, Numix/16x16/actions/gtk-select-color.svg, Numix/22x22/actions/gtk-select-color.svg, Numix/24x24/actions/gtk-select-color.svg, Numix/256x256/actions/gtk-select-color.svg, Numix/32x32/actions/gtk-select-color.svg, Numix/48x48/actions/gtk-select-color.svg, Numix/64x64/actions/gtk-select-color.svg
No idea why this was reverted back, but the new style did not survive all pull requests. Probably my fault
=> Adds gtk-select-colour again

Numix/128x128/actions/gtk-edit.svg, Numix/16x16/actions/gtk-edit.svg, Numix/22x22/actions/gtk-edit.svg, Numix/24x24/actions/gtk-edit.svg, Numix/256x256/actions/gtk-edit.svg, Numix/32x32/actions/gtk-edit.svg, Numix/48x48/actions/gtk-edit.svg, Numix/64x64/actions/gtk-edit.svg
=> Adds gtk-edit

Numix-Light/16x16/status/spotify-indicator.svg, Numix-Light/22x22/status/spotify-indicator.svg, Numix-Light/24x24/status/spotify-indicator.svg, Numix/16x16/status/spotify-indicator.svg, Numix/22x22/status/spotify-indicator.svg, Numix/24x24/status/spotify-indicator.svg
=> symlink spotify-client to spotify-indicator

Numix/128x128/devices/device_mem.svg, Numix/128x128/devices/device_pci.svg, Numix/128x128/devices/device_usb.svg, Numix/16x16/devices/device_mem.svg, Numix/16x16/devices/device_pci.svg, Numix/16x16/devices/device_usb.svg, Numix/22x22/devices/device_mem.svg, Numix/22x22/devices/device_pci.svg, Numix/22x22/devices/device_usb.svg, Numix/24x24/devices/device_mem.svg, Numix/24x24/devices/device_pci.svg, Numix/24x24/devices/device_usb.svg, Numix/256x256/devices/device_mem.svg, Numix/256x256/devices/device_pci.svg, Numix/256x256/devices/device_usb.svg, Numix/32x32/devices/device_mem.svg, Numix/32x32/devices/device_pci.svg, Numix/32x32/devices/device_usb.svg, Numix/48x48/devices/device_mem.svg, Numix/48x48/devices/device_pci.svg, Numix/48x48/devices/device_usb.svg, Numix/64x64/devices/device_mem.svg, Numix/64x64/devices/device_pci.svg, Numix/64x64/devices/device_usb.svg
=> some symlinks for virt-manager

Numix/16x16/status/pushbullet-indicator-dark.svg, Numix/16x16/status/pushbullet-indicator-light.svg, Numix/16x16/status/pushbullet-indicator-sync0-dark.svg, Numix/16x16/status/pushbullet-indicator-sync0-light.svg, Numix/16x16/status/pushbullet-indicator-sync1-dark.svg, Numix/16x16/status/pushbullet-indicator-sync1-light.svg, Numix/16x16/status/pushbullet-indicator-sync2-dark.svg, Numix/16x16/status/pushbullet-indicator-sync2-light.svg, Numix/16x16/status/pushbullet-indicator-sync3-dark.svg, Numix/16x16/status/pushbullet-indicator-sync3-light.svg, Numix/22x22/status/pushbullet-indicator-dark.svg, Numix/22x22/status/pushbullet-indicator-light.svg, Numix/22x22/status/pushbullet-indicator-sync0-dark.svg, Numix/22x22/status/pushbullet-indicator-sync0-light.svg, Numix/22x22/status/pushbullet-indicator-sync1-dark.svg, Numix/22x22/status/pushbullet-indicator-sync1-light.svg, Numix/22x22/status/pushbullet-indicator-sync2-dark.svg, Numix/22x22/status/pushbullet-indicator-sync2-light.svg, Numix/22x22/status/pushbullet-indicator-sync3-dark.svg, Numix/22x22/status/pushbullet-indicator-sync3-light.svg, Numix/24x24/status/pushbullet-indicator-dark.svg, Numix/24x24/status/pushbullet-indicator-light.svg, Numix/24x24/status/pushbullet-indicator-sync0-dark.svg, Numix/24x24/status/pushbullet-indicator-sync0-light.svg, Numix/24x24/status/pushbullet-indicator-sync1-dark.svg, Numix/24x24/status/pushbullet-indicator-sync1-light.svg, Numix/24x24/status/pushbullet-indicator-sync2-dark.svg, Numix/24x24/status/pushbullet-indicator-sync2-light.svg, Numix/24x24/status/pushbullet-indicator-sync3-dark.svg, Numix/24x24/status/pushbullet-indicator-sync3-light.svg
status icons for pushbullet indicator
=> Adds pushbullet indicator icons

Numix/128x128/actions/object-rotate.svg, Numix/16x16/actions/object-rotate.svg, Numix/22x22/actions/object-rotate.svg, Numix/24x24/actions/object-rotate.svg, Numix/256x256/actions/object-rotate.svg, Numix/32x32/actions/object-rotate.svg, Numix/48x48/actions/object-rotate.svg, Numix/64x64/actions/object-rotate.svg, Numix/96x96/actions/object-rotate.svg
=> symlink object-rotate-right to object-rotate

Numix/128x128/actions/gtk-page-setup.svg, Numix/16x16/actions/gtk-page-setup.svg, Numix/22x22/actions/gtk-page-setup.svg, Numix/24x24/actions/gtk-page-setup.svg, Numix/256x256/actions/gtk-page-setup.svg, Numix/32x32/actions/gtk-page-setup.svg, Numix/48x48/actions/gtk-page-setup.svg, Numix/64x64/actions/gtk-page-setup.svg
=> Adds gtk-page-setup

Numix/128x128/status/gtk-caps-lock-warning.svg, Numix/16x16/status/gtk-caps-lock-warning.svg, Numix/22x22/status/gtk-caps-lock-warning.svg, Numix/24x24/status/gtk-caps-lock-warning.svg, Numix/256x256/status/gtk-caps-lock-warning.svg, Numix/32x32/status/gtk-caps-lock-warning.svg, Numix/48x48/status/gtk-caps-lock-warning.svg, Numix/64x64/status/gtk-caps-lock-warning.svg, Numix/scalable/status/gtk-caps-lock-warning.svg
=> Adds gtk-caps-lock-warning symlinks

Numix/128x128/actions/gtk-index.svg, Numix/16x16/actions/gtk-index.svg, Numix/22x22/actions/gtk-index.svg, Numix/24x24/actions/gtk-index.svg, Numix/256x256/actions/gtk-index.svg, Numix/32x32/actions/gtk-index.svg, Numix/48x48/actions/gtk-index.svg, Numix/64x64/actions/gtk-index.svg
=> Adds gtk-index

Numix/128x128/actions/gtk-select-font.svg, Numix/16x16/actions/gtk-select-font.svg, Numix/22x22/actions/gtk-select-font.svg, Numix/24x24/actions/gtk-select-font.svg, Numix/256x256/actions/gtk-select-font.svg, Numix/32x32/actions/gtk-select-font.svg, Numix/48x48/actions/gtk-select-font.svg, Numix/64x64/actions/gtk-select-font.svg
=> Adds gtk-select-font

Numix/128x128/actions/gtk-dnd-multiple.svg, Numix/128x128/actions/gtk-dnd.svg, Numix/16x16/actions/gtk-dnd-multiple.svg, Numix/16x16/actions/gtk-dnd.svg, Numix/22x22/actions/gtk-dnd-multiple.svg, Numix/22x22/actions/gtk-dnd.svg, Numix/24x24/actions/gtk-dnd-multiple.svg, Numix/24x24/actions/gtk-dnd.svg, Numix/256x256/actions/gtk-dnd-multiple.svg, Numix/256x256/actions/gtk-dnd.svg, Numix/32x32/actions/gtk-dnd-multiple.svg, Numix/32x32/actions/gtk-dnd.svg, Numix/48x48/actions/gtk-dnd-multiple.svg, Numix/48x48/actions/gtk-dnd.svg, Numix/64x64/actions/gtk-dnd-multiple.svg, Numix/64x64/actions/gtk-dnd.svg
`gtk-dnd` from #315. Might be too subtle but this was the only icon I was able to come up with...
=> Adds gtk-dnd

Numix-Light/scalable/status/network-wired-disconnected-symbolic.svg, Numix-Light/scalable/status/network-wired-offline-symbolic.svg, Numix/scalable/status/network-wired-disconnected-symbolic.svg, Numix/scalable/status/network-wired-offline-symbolic.svg
Fixes https://github.com/numixproject/numix-icon-theme/issues/547.
=> Added network-wired-disconnected-symbolic.svg

Numix/128x128/actions/package-broken.svg, Numix/128x128/actions/package-new.svg, Numix/16x16/actions/package-broken.svg, Numix/16x16/actions/package-new.svg, Numix/22x22/actions/package-broken.svg, Numix/22x22/actions/package-new.svg, Numix/24x24/actions/package-broken.svg, Numix/24x24/actions/package-new.svg, Numix/256x256/actions/package-broken.svg, Numix/256x256/actions/package-new.svg, Numix/32x32/actions/package-broken.svg, Numix/32x32/actions/package-new.svg, Numix/48x48/actions/package-broken.svg, Numix/48x48/actions/package-new.svg, Numix/64x64/actions/package-broken.svg, Numix/64x64/actions/package-new.svg
=> Adds package-broken

Numix/128x128/actions/package-downgrade.svg, Numix/128x128/actions/package-installed-outdated.svg, Numix/128x128/actions/package-installed-updated.svg, Numix/128x128/actions/package-upgrade.svg, Numix/16x16/actions/package-installed-outdated.svg, Numix/16x16/actions/package-installed-updated.svg, Numix/22x22/actions/package-installed-outdated.svg, Numix/22x22/actions/package-installed-updated.svg, Numix/24x24/actions/package-installed-outdated.svg, Numix/24x24/actions/package-installed-updated.svg, Numix/256x256/actions/package-installed-outdated.svg, Numix/256x256/actions/package-installed-updated.svg, Numix/32x32/actions/package-installed-outdated.svg, Numix/32x32/actions/package-installed-updated.svg, Numix/48x48/actions/package-installed-outdated.svg, Numix/48x48/actions/package-installed-updated.svg, Numix/64x64/actions/package-installed-outdated.svg, Numix/64x64/actions/package-installed-updated.svg
=> Adds package-installed-outdated and package-installed-updated

Numix/128x128/actions/package-available-locked.svg, Numix/128x128/actions/package-available.svg, Numix/16x16/actions/package-available-locked.svg, Numix/16x16/actions/package-available.svg, Numix/22x22/actions/package-available-locked.svg, Numix/22x22/actions/package-available.svg, Numix/24x24/actions/package-available-locked.svg, Numix/24x24/actions/package-available.svg, Numix/256x256/actions/package-available-locked.svg, Numix/256x256/actions/package-available.svg, Numix/32x32/actions/package-available-locked.svg, Numix/32x32/actions/package-available.svg, Numix/48x48/actions/package-available-locked.svg, Numix/48x48/actions/package-available.svg, Numix/64x64/actions/package-available-locked.svg, Numix/64x64/actions/package-available.svg
=> Adds package-available package-available-locked

Numix/128x128/mimetypes/text-x-emacs-lisp.svg, Numix/16x16/mimetypes/text-x-emacs-lisp.svg, Numix/22x22/mimetypes/text-x-emacs-lisp.svg, Numix/24x24/mimetypes/text-x-emacs-lisp.svg, Numix/256x256/mimetypes/text-x-emacs-lisp.svg, Numix/32x32/mimetypes/text-x-emacs-lisp.svg, Numix/48x48/mimetypes/text-x-emacs-lisp.svg, Numix/64x64/mimetypes/text-x-emacs-lisp.svg
=> Mimetype for Emacs Lisp

Numix/128x128/mimetypes/text-x-iptables.svg, Numix/16x16/mimetypes/text-x-iptables.svg, Numix/22x22/mimetypes/text-x-iptables.svg, Numix/24x24/mimetypes/text-x-iptables.svg, Numix/256x256/mimetypes/text-x-iptables.svg, Numix/32x32/mimetypes/text-x-iptables.svg, Numix/48x48/mimetypes/text-x-iptables.svg, Numix/64x64/mimetypes/text-x-iptables.svg
=> Mimetype for iptables configuration files

Numix/128x128/mimetypes/text-x-haskell.svg, Numix/128x128/mimetypes/text-x-scheme.svg, Numix/16x16/mimetypes/text-x-haskell.svg, Numix/16x16/mimetypes/text-x-scheme.svg, Numix/22x22/mimetypes/text-x-haskell.svg, Numix/22x22/mimetypes/text-x-scheme.svg, Numix/24x24/mimetypes/text-x-haskell.svg, Numix/24x24/mimetypes/text-x-scheme.svg, Numix/256x256/mimetypes/text-x-haskell.svg, Numix/256x256/mimetypes/text-x-scheme.svg, Numix/32x32/mimetypes/text-x-haskell.svg, Numix/32x32/mimetypes/text-x-scheme.svg, Numix/48x48/mimetypes/text-x-haskell.svg, Numix/48x48/mimetypes/text-x-scheme.svg, Numix/64x64/mimetypes/text-x-haskell.svg, Numix/64x64/mimetypes/text-x-scheme.svg
=> Mimetype for Scheme and Haskell source files

Numix/128x128/actions/package-available-new.svg, Numix/128x128/actions/package-installed-locked.svg, Numix/16x16/actions/package-available-new.svg, Numix/16x16/actions/package-installed-locked.svg, Numix/22x22/actions/package-available-new.svg, Numix/22x22/actions/package-installed-locked.svg, Numix/24x24/actions/package-available-new.svg, Numix/24x24/actions/package-installed-locked.svg, Numix/256x256/actions/package-available-new.svg, Numix/256x256/actions/package-installed-locked.svg, Numix/32x32/actions/package-available-new.svg, Numix/32x32/actions/package-installed-locked.svg, Numix/48x48/actions/package-available-new.svg, Numix/48x48/actions/package-installed-locked.svg, Numix/64x64/actions/package-available-new.svg, Numix/64x64/actions/package-installed-locked.svg
two more for #184. I have to think about the last one
=> package-installed-locked and symlink to package-available

Numix/128x128/actions/package-supported.svg, Numix/16x16/actions/package-supported.svg, Numix/22x22/actions/package-supported.svg, Numix/24x24/actions/package-supported.svg, Numix/256x256/actions/package-supported.svg, Numix/32x32/actions/package-supported.svg, Numix/48x48/actions/package-supported.svg, Numix/64x64/actions/package-supported.svg
=> Adds package-supported fixes #184

Numix/128x128/devices/multimedia-player-ipod-mini-blue.svg, Numix/16x16/devices/multimedia-player-ipod-mini-blue.svg, Numix/22x22/devices/multimedia-player-ipod-mini-blue.svg, Numix/24x24/devices/multimedia-player-ipod-mini-blue.svg, Numix/256x256/devices/multimedia-player-ipod-mini-blue.svg, Numix/32x32/devices/multimedia-player-ipod-mini-blue.svg, Numix/48x48/devices/multimedia-player-ipod-mini-blue.svg, Numix/64x64/devices/multimedia-player-ipod-mini-blue.svg
This will add a symlink for ``` multimedia-player-ipod-mini-blue``` in #273, other icons must be created, for ```folder-sound``` i can symlink it to ```folder-music```
=> a symlink for clementine

Numix/128x128/places/folder-sound.svg, Numix/16x16/places/folder-sound.svg, Numix/22x22/places/folder-sound.svg, Numix/24x24/places/folder-sound.svg, Numix/256x256/places/folder-sound.svg, Numix/32x32/places/folder-sound.svg, Numix/48x48/places/folder-sound.svg, Numix/64x64/places/folder-sound.svg, Numix/96x96/places/folder-sound.svg
=> one more symlink for clementine

Numix/128x128/mimetypes/application-x-xpinstall.svg, Numix/16x16/mimetypes/application-x-xpinstall.svg, Numix/22x22/mimetypes/application-x-xpinstall.svg, Numix/24x24/mimetypes/application-x-xpinstall.svg, Numix/256x256/mimetypes/application-x-xpinstall.svg, Numix/32x32/mimetypes/application-x-xpinstall.svg, Numix/48x48/mimetypes/application-x-xpinstall.svg, Numix/64x64/mimetypes/application-x-xpinstall.svg
=> symlink xpinstall mimetype to extension

Numix/128x128/mimetypes/application-x-object.svg, Numix/16x16/mimetypes/application-x-object.svg, Numix/22x22/mimetypes/application-x-object.svg, Numix/24x24/mimetypes/application-x-object.svg, Numix/256x256/mimetypes/application-x-object.svg, Numix/32x32/mimetypes/application-x-object.svg, Numix/48x48/mimetypes/application-x-object.svg, Numix/64x64/mimetypes/application-x-object.svg
Fixes #293
Symlinks to ``application-octet-stream.svg``
=> C object file mimetype enhancement

Numix-Light/scalable/devices/drive-harddisk-symbolic-backup2.svg, Numix-Light/scalable/devices/drive-harddisk-symbolic.svg, Numix/scalable/devices/drive-harddisk-symbolic-backup.svg, Numix/scalable/devices/drive-harddisk-symbolic-backup2.svg
Fixes https://github.com/numixproject/numix-icon-theme/issues/578.
=> Made drive-harddisk-symbolic.svg consistent

Numix-Light/scalable/devices/battery-symbolic.svg, Numix/scalable/devices/battery-symbolic.svg
Fixes https://github.com/numixproject/numix-icon-theme/issues/581. (symlink)
=> Added battery-symbolic.svg

Numix-Light/scalable/devices/drive-harddisk-ieee1394-symbolic.svg, Numix-Light/scalable/devices/drive-harddisk-system-symbolic.svg, Numix-Light/scalable/devices/drive-harddisk-usb-symbolic.svg, Numix/scalable/devices/drive-harddisk-ieee1394-symbolic.svg, Numix/scalable/devices/drive-harddisk-system-symbolic.svg, Numix/scalable/devices/drive-harddisk-usb-symbolic.svg
Fixes https://github.com/numixproject/numix-icon-theme/issues/583. (symlinks)
=> Added drive-harddisk-*-symbolic.svg

Numix/128x128/mimetypes/text-x-qml.svg, Numix/16x16/mimetypes/text-x-qml.svg, Numix/22x22/mimetypes/text-x-qml.svg, Numix/24x24/mimetypes/text-x-qml.svg, Numix/256x256/mimetypes/text-x-qml.svg, Numix/32x32/mimetypes/text-x-qml.svg, Numix/48x48/mimetypes/text-x-qml.svg, Numix/64x64/mimetypes/text-x-qml.svg
=> QML mimetype icons

Numix/128x128/mimetypes/text-rtf.svg, Numix/16x16/mimetypes/text-rtf.svg, Numix/22x22/mimetypes/text-rtf.svg, Numix/24x24/mimetypes/text-rtf.svg, Numix/256x256/mimetypes/text-rtf.svg, Numix/32x32/mimetypes/text-rtf.svg, Numix/48x48/mimetypes/text-rtf.svg, Numix/64x64/mimetypes/text-rtf.svg
=> Symlinks for text-rtf mimetype

Numix/128x128/categories/preferences-calendar-and-tasks.svg, Numix/16x16/categories/preferences-calendar-and-tasks.svg, Numix/22x22/categories/preferences-calendar-and-tasks.svg, Numix/24x24/categories/preferences-calendar-and-tasks.svg, Numix/256x256/categories/preferences-calendar-and-tasks.svg, Numix/32x32/categories/preferences-calendar-and-tasks.svg, Numix/48x48/categories/preferences-calendar-and-tasks.svg, Numix/64x64/categories/preferences-calendar-and-tasks.svg
The current symlink did not really work with the other designs from `categories`. I think I came up with a more appropriate design :)
=> Adds better design for preferences-calendar-and-task

Numix-Light/16x16/status/megasync-status-disconnected.svg, Numix-Light/16x16/status/megasync-status-ok.svg, Numix-Light/16x16/status/megasync-status-paused.svg, Numix-Light/16x16/status/megasync-status-syncing.svg, Numix-Light/22x22/status/megasync-status-disconnected.svg, Numix-Light/22x22/status/megasync-status-ok.svg, Numix-Light/22x22/status/megasync-status-paused.svg, Numix-Light/22x22/status/megasync-status-syncing.svg, Numix-Light/24x24/status/megasync-status-disconnected.svg, Numix-Light/24x24/status/megasync-status-ok.svg, Numix-Light/24x24/status/megasync-status-paused.svg, Numix-Light/24x24/status/megasync-status-syncing.svg, Numix/16x16/status/megasync-status-disconnected.svg, Numix/16x16/status/megasync-status-ok.svg, Numix/16x16/status/megasync-status-paused.svg, Numix/16x16/status/megasync-status-syncing.svg, Numix/22x22/status/megasync-status-disconnected.svg, Numix/22x22/status/megasync-status-ok.svg, Numix/22x22/status/megasync-status-paused.svg, Numix/22x22/status/megasync-status-syncing.svg, Numix/24x24/status/megasync-status-disconnected.svg, Numix/24x24/status/megasync-status-ok.svg, Numix/24x24/status/megasync-status-paused.svg, Numix/24x24/status/megasync-status-syncing.svg
MMegasync status icons from #613
=> Adds megasync status icons

Numix-Light/16x16/status/google-music-manager-panel.svg, Numix-Light/22x22/status/google-music-manager-panel.svg, Numix-Light/24x24/status/google-music-manager-panel.svg, Numix/16x16/status/google-music-manager-panel.svg, Numix/22x22/status/google-music-manager-panel.svg, Numix/24x24/status/google-music-manager-panel.svg
=> Adds tray icons for google-music-manager

Numix-Light/16x16/panel/fluxgui-panel.svg, Numix-Light/22x22/panel/fluxgui-panel.svg, Numix-Light/24x24/panel/fluxgui-panel.svg, Numix/16x16/panel/fluxgui-panel.svg, Numix/22x22/panel/fluxgui-panel.svg, Numix/24x24/panel/fluxgui-panel.svg
fluxgui-panel icons in `panel` #636
=> Adds fluxgui panel icons fixes #636

Numix/128x128/actions/document-edit.svg, Numix/16x16/actions/document-edit.svg, Numix/22x22/actions/document-edit.svg, Numix/24x24/actions/document-edit.svg, Numix/256x256/actions/document-edit.svg, Numix/32x32/actions/document-edit.svg, Numix/48x48/actions/document-edit.svg, Numix/64x64/actions/document-edit.svg
=> Added symlinks for document-edit action icon

Numix/128x128/actions/document-close.svg, Numix/16x16/actions/document-close.svg, Numix/22x22/actions/document-close.svg, Numix/24x24/actions/document-close.svg, Numix/256x256/actions/document-close.svg, Numix/32x32/actions/document-close.svg, Numix/48x48/actions/document-close.svg, Numix/64x64/actions/document-close.svg
=> Added document-close action icon

Numix/128x128/actions/edit.svg, Numix/16x16/actions/edit.svg, Numix/22x22/actions/edit.svg, Numix/24x24/actions/edit.svg, Numix/256x256/actions/edit.svg, Numix/32x32/actions/edit.svg, Numix/48x48/actions/edit.svg, Numix/64x64/actions/edit.svg
=> Symlinks for the 'edit' action icon

Numix/128x128/actions/edit-flag.svg, Numix/128x128/actions/edit-mark.svg, Numix/16x16/actions/edit-flag.svg, Numix/16x16/actions/edit-mark.svg, Numix/22x22/actions/edit-flag.svg, Numix/22x22/actions/edit-mark.svg, Numix/24x24/actions/edit-flag.svg, Numix/24x24/actions/edit-mark.svg, Numix/256x256/actions/edit-flag.svg, Numix/256x256/actions/edit-mark.svg, Numix/32x32/actions/edit-flag.svg, Numix/32x32/actions/edit-mark.svg, Numix/48x48/actions/edit-flag.svg, Numix/48x48/actions/edit-mark.svg, Numix/64x64/actions/edit-flag.svg, Numix/64x64/actions/edit-mark.svg
From #437 
Analogous to the elementary theme ``edit-mark`` as symlink to ``edit-flag``.
=> Added edit-flag and edit-mark action icons

Numix/128x128/actions/tag-new.svg, Numix/16x16/actions/tag-new.svg, Numix/22x22/actions/tag-new.svg, Numix/24x24/actions/tag-new.svg, Numix/256x256/actions/tag-new.svg, Numix/32x32/actions/tag-new.svg, Numix/48x48/actions/tag-new.svg, Numix/64x64/actions/tag-new.svg
=> Added tag-new action icons

Numix/128x128/actions/open-menu.svg, Numix/16x16/actions/open-menu.svg, Numix/22x22/actions/open-menu.svg, Numix/24x24/actions/open-menu.svg, Numix/256x256/actions/open-menu.svg, Numix/32x32/actions/open-menu.svg, Numix/48x48/actions/open-menu.svg, Numix/64x64/actions/open-menu.svg
=> Added open-menu action icons

Numix/128x128/mimetypes/application-pgp.svg, Numix/16x16/mimetypes/application-pgp.svg, Numix/22x22/mimetypes/application-pgp.svg, Numix/24x24/mimetypes/application-pgp.svg, Numix/256x256/mimetypes/application-pgp.svg, Numix/32x32/mimetypes/application-pgp.svg, Numix/48x48/mimetypes/application-pgp.svg, Numix/64x64/mimetypes/application-pgp.svg
=> Added symlinks for application-pgp

Numix/128x128/actions/edit-flag.svg, Numix/16x16/actions/edit-flag.svg, Numix/22x22/actions/edit-flag.svg, Numix/24x24/actions/edit-flag.svg, Numix/256x256/actions/edit-flag.svg, Numix/32x32/actions/edit-flag.svg, Numix/48x48/actions/edit-flag.svg, Numix/64x64/actions/edit-flag.svg
=> Tweaked edit-flag position

Numix/128x128/actions/gtk-spell-check.svg, Numix/128x128/actions/stock-spell-check.svg, Numix/16x16/actions/gtk-spell-check.svg, Numix/16x16/actions/stock-spell-check.svg, Numix/22x22/actions/gtk-spell-check.svg, Numix/22x22/actions/stock-spell-check.svg, Numix/24x24/actions/gtk-spell-check.svg, Numix/24x24/actions/stock-spell-check.svg, Numix/256x256/actions/gtk-spell-check.svg, Numix/256x256/actions/stock-spell-check.svg, Numix/32x32/actions/gtk-spell-check.svg, Numix/32x32/actions/stock-spell-check.svg, Numix/48x48/actions/gtk-spell-check.svg, Numix/48x48/actions/stock-spell-check.svg, Numix/64x64/actions/gtk-spell-check.svg, Numix/64x64/actions/stock-spell-check.svg
Found them in the gnome theme.
=> Added symlinks for gtk-spell-check and stock-spell-check

Numix/128x128/actions/mail-forwarded.svg, Numix/16x16/actions/mail-forwarded.svg, Numix/22x22/actions/mail-forwarded.svg, Numix/24x24/actions/mail-forwarded.svg, Numix/256x256/actions/mail-forwarded.svg, Numix/32x32/actions/mail-forwarded.svg, Numix/48x48/actions/mail-forwarded.svg, Numix/64x64/actions/mail-forwarded.svg
On the lists in #437 and #580.
=> Symlinks for mail-forwarded

Numix/128x128/actions/document-save-all.svg, Numix/16x16/actions/document-save-all.svg, Numix/22x22/actions/document-save-all.svg, Numix/24x24/actions/document-save-all.svg, Numix/256x256/actions/document-save-all.svg, Numix/32x32/actions/document-save-all.svg, Numix/48x48/actions/document-save-all.svg, Numix/64x64/actions/document-save-all.svg
=> Symlinks for document-save-all action icon

Numix/128x128/actions/configure.svg, Numix/16x16/actions/configure.svg, Numix/22x22/actions/configure.svg, Numix/24x24/actions/configure.svg, Numix/256x256/actions/configure.svg, Numix/32x32/actions/configure.svg, Numix/48x48/actions/configure.svg, Numix/64x64/actions/configure.svg
=> Symlinks for configure action icon

Numix/128x128/actions/rating.svg, Numix/16x16/actions/rating.svg, Numix/22x22/actions/rating.svg, Numix/24x24/actions/rating.svg, Numix/256x256/actions/rating.svg, Numix/32x32/actions/rating.svg, Numix/48x48/actions/rating.svg, Numix/64x64/actions/rating.svg
=> Added rating action icon

Numix-Light/16x16/status/weather-windy.svg, Numix-Light/22x22/status/weather-windy.svg, Numix-Light/24x24/status/weather-windy.svg, Numix/16x16/status/weather-windy.svg, Numix/22x22/status/weather-windy.svg, Numix/24x24/status/weather-windy.svg
I forgot to add those icons...
=> Adds weather-windy

Numix/128x128/actions/help-info.svg, Numix/128x128/actions/help.svg, Numix/16x16/actions/help-info.svg, Numix/16x16/actions/help.svg, Numix/22x22/actions/help-info.svg, Numix/22x22/actions/help.svg, Numix/24x24/actions/help-info.svg, Numix/24x24/actions/help.svg, Numix/256x256/actions/help-info.svg, Numix/256x256/actions/help.svg, Numix/32x32/actions/help-info.svg, Numix/32x32/actions/help.svg, Numix/48x48/actions/help-info.svg, Numix/48x48/actions/help.svg, Numix/64x64/actions/help-info.svg, Numix/64x64/actions/help.svg
In preparation for fixing https://github.com/numixproject/numix-icon-theme-circle/issues/2412.
=> Added help and help-info action icons

Numix/128x128/actions/documentinfo.svg, Numix/128x128/actions/insert-table.svg, Numix/16x16/actions/documentinfo.svg, Numix/16x16/actions/insert-table.svg, Numix/22x22/actions/documentinfo.svg, Numix/22x22/actions/insert-table.svg, Numix/24x24/actions/documentinfo.svg, Numix/24x24/actions/insert-table.svg, Numix/256x256/actions/documentinfo.svg, Numix/256x256/actions/insert-table.svg, Numix/32x32/actions/documentinfo.svg, Numix/32x32/actions/insert-table.svg, Numix/48x48/actions/documentinfo.svg, Numix/48x48/actions/insert-table.svg, Numix/64x64/actions/documentinfo.svg, Numix/64x64/actions/insert-table.svg
=> Symlinks for documentinfo and insert-table action icons

Numix/128x128/actions/stock_calendar-and-taks.svg, Numix/16x16/actions/stock_calendar-and-taks.svg, Numix/22x22/actions/stock_calendar-and-taks.svg, Numix/24x24/actions/stock_calendar-and-taks.svg, Numix/256x256/actions/stock_calendar-and-taks.svg, Numix/32x32/actions/stock_calendar-and-taks.svg, Numix/48x48/actions/stock_calendar-and-taks.svg, Numix/64x64/actions/stock_calendar-and-taks.svg
Another one used by Evolution.
To be removed from Circle.
=> Added stock_calendar-and-tasks

Numix/128x128/mimetypes/application-font-snf.svg, Numix/16x16/actions/application-font-snf.svg, Numix/22x22/mimetypes/application-font-snf.svg, Numix/24x24/mimetypes/application-font-snf.svg, Numix/256x256/mimetypes/application-font-snf.svg, Numix/32x32/mimetypes/application-font-snf.svg, Numix/48x48/mimetypes/application-font-snf.svg, Numix/64x64/mimetypes/application-font-snf.svg
=> Symlinks for application-font-snf mimetype

Numix/128x128/actions/transform-crop.svg, Numix/16x16/actions/transform-crop.svg, Numix/22x22/actions/transform-crop.svg, Numix/24x24/actions/transform-crop.svg, Numix/256x256/actions/transform-crop.svg, Numix/32x32/actions/transform-crop.svg, Numix/48x48/actions/transform-crop.svg, Numix/64x64/actions/transform-crop.svg
=> Symlinks for transform-crop action

Numix/128x128/categories/preferences-desktop-accessibility.svg, Numix/16x16/categories/preferences-desktop-accessibility.svg, Numix/22x22/categories/preferences-desktop-accessibility.svg, Numix/24x24/categories/preferences-desktop-accessibility.svg, Numix/256x256/categories/preferences-desktop-accessibility.svg, Numix/32x32/categories/preferences-desktop-accessibility.svg, Numix/48x48/categories/preferences-desktop-accessibility.svg, Numix/64x64/categories/preferences-desktop-accessibility.svg
Starting with the low hanging fruits from #437 :)
=> Adds preferences-desktop-accessibility

Numix/128x128/actions/active-notes.svg, Numix/16x16/actions/active-notes.svg, Numix/22x22/actions/active-notes.svg, Numix/24x24/actions/active-notes.svg, Numix/256x256/actions/active-notes.svg, Numix/32x32/actions/active-notes.svg, Numix/48x48/actions/active-notes.svg, Numix/64x64/actions/active-notes.svg
Forgot this in my last note PR.
=> Added active-notes

Numix/128x128/status/task-due.svg, Numix/128x128/status/task-past-due.svg, Numix/16x16/status/task-due.svg, Numix/16x16/status/task-past-due.svg, Numix/22x22/status/task-due.svg, Numix/22x22/status/task-past-due.svg, Numix/24x24/status/task-due.svg, Numix/24x24/status/task-past-due.svg, Numix/256x256/status/task-due.svg, Numix/256x256/status/task-past-due.svg, Numix/32x32/status/task-due.svg, Numix/32x32/status/task-past-due.svg, Numix/48x48/status/task-due.svg, Numix/48x48/status/task-past-due.svg, Numix/64x64/status/task-due.svg, Numix/64x64/status/task-past-due.svg
=> Added task-due and task-past-due status icons

Numix/128x128/status/printer-printing.svg, Numix/16x16/status/printer-printing.svg, Numix/22x22/status/printer-printing.svg, Numix/24x24/status/printer-printing.svg, Numix/256x256/status/printer-printing.svg, Numix/32x32/status/printer-printing.svg, Numix/48x48/status/printer-printing.svg, Numix/64x64/status/printer-printing.svg
=> Added printer-printing status icons

Numix/128x128/mimetypes/application-x-java-applet.svg, Numix/16x16/mimetypes/application-x-java-applet.svg, Numix/22x22/mimetypes/application-x-java-applet.svg, Numix/24x24/mimetypes/application-x-java-applet.svg, Numix/256x256/mimetypes/application-x-java-applet.svg, Numix/32x32/mimetypes/application-x-java-applet.svg, Numix/48x48/mimetypes/application-x-java-applet.svg, Numix/64x64/mimetypes/application-x-java-applet.svg
=> Symlinks for application-x-java-applet mimetype

Numix/128x128/status/airplane-mode.svg, Numix/16x16/status/airplane-mode.svg, Numix/22x22/status/airplane-mode.svg, Numix/24x24/status/airplane-mode.svg, Numix/256x256/status/airplane-mode.svg, Numix/32x32/status/airplane-mode.svg, Numix/48x48/status/airplane-mode.svg, Numix/64x64/status/airplane-mode.svg
=> Adds airplane-mode.svg

Numix/128x128/categories/applications-education.svg, Numix/16x16/categories/applications-education.svg, Numix/22x22/categories/applications-education.svg, Numix/24x24/categories/applications-education.svg, Numix/256x256/categories/applications-education.svg, Numix/32x32/categories/applications-education.svg, Numix/48x48/categories/applications-education.svg, Numix/64x64/categories/applications-education.svg
=> Adds applications-education

Numix/128x128/actions/event-new.svg, Numix/16x16/actions/event-new.svg, Numix/22x22/actions/event-new.svg, Numix/24x24/actions/event-new.svg, Numix/256x256/actions/event-new.svg, Numix/32x32/actions/event-new.svg, Numix/48x48/actions/event-new.svg, Numix/64x64/actions/event-new.svg
=> Symlinks for event-new action

Numix/128x128/actions/format-text-none.svg, Numix/16x16/actions/format-text-none.svg, Numix/22x22/actions/format-text-none.svg, Numix/24x24/actions/format-text-none.svg, Numix/256x256/actions/format-text-none.svg, Numix/32x32/actions/format-text-none.svg, Numix/48x48/actions/format-text-none.svg, Numix/64x64/actions/format-text-none.svg
From #437.
The 9th changed file is an alignment fix for existing icon.
=> Added format-text-none action

Numix/128x128/actions/mail-archive.svg, Numix/128x128/places/mail-mailbox.svg, Numix/16x16/actions/mail-archive.svg, Numix/16x16/places/mail-mailbox.svg, Numix/22x22/actions/mail-archive.svg, Numix/22x22/places/mail-mailbox.svg, Numix/24x24/actions/mail-archive.svg, Numix/24x24/places/mail-mailbox.svg, Numix/256x256/actions/mail-archive.svg, Numix/256x256/places/mail-mailbox.svg, Numix/32x32/actions/mail-archive.svg, Numix/32x32/places/mail-mailbox.svg, Numix/48x48/actions/mail-archive.svg, Numix/48x48/places/mail-mailbox.svg, Numix/64x64/actions/mail-archive.svg, Numix/64x64/places/mail-mailbox.svg
=> Added mail-archive and mail-mailbox

Numix/128x128/status/changes-allow.svg, Numix/128x128/status/changes-prevent.svg, Numix/16x16/status/changes-allow.svg, Numix/16x16/status/changes-prevent.svg, Numix/22x22/status/changes-allow.svg, Numix/22x22/status/changes-prevent.svg, Numix/24x24/status/changes-allow.svg, Numix/24x24/status/changes-prevent.svg, Numix/256x256/status/changes-allow.svg, Numix/256x256/status/changes-prevent.svg, Numix/32x32/status/changes-allow.svg, Numix/32x32/status/changes-prevent.svg, Numix/48x48/status/changes-allow.svg, Numix/48x48/status/changes-prevent.svg, Numix/64x64/status/changes-allow.svg, Numix/64x64/status/changes-prevent.svg
=> Added changes-allow and changes-prevent status icons

Numix/128x128/status/stock_appointment-reminder-excl.svg, Numix/128x128/status/stock_appointment-reminder.svg, Numix/16x16/status/stock_appointment-reminder-excl.svg, Numix/16x16/status/stock_appointment-reminder.svg, Numix/22x22/status/stock_appointment-reminder-excl.svg, Numix/22x22/status/stock_appointment-reminder.svg, Numix/24x24/status/stock_appointment-reminder-excl.svg, Numix/24x24/status/stock_appointment-reminder.svg, Numix/256x256/status/stock_appointment-reminder-excl.svg, Numix/256x256/status/stock_appointment-reminder.svg, Numix/32x32/status/stock_appointment-reminder-excl.svg, Numix/32x32/status/stock_appointment-reminder.svg, Numix/48x48/status/stock_appointment-reminder-excl.svg, Numix/48x48/status/stock_appointment-reminder.svg, Numix/64x64/status/stock_appointment-reminder-excl.svg, Numix/64x64/status/stock_appointment-reminder.svg
Found those in the ``gnome`` theme.
=> stock_appointment-reminder(-excl) status icons

Numix/128x128/categories/preferences-system-time.svg, Numix/16x16/categories/preferences-system-time.svg, Numix/22x22/categories/preferences-system-time.svg, Numix/24x24/categories/preferences-system-time.svg, Numix/256x256/categories/preferences-system-time.svg, Numix/32x32/categories/preferences-system-time.svg, Numix/48x48/categories/preferences-system-time.svg, Numix/64x64/categories/preferences-system-time.svg
One from #437. Since it is a preferences-icon I checked and a circle icon already exists
=> Adds preferences-system-time to base

Numix/128x128/actions/journal-new.svg, Numix/16x16/actions/journal-new.svg, Numix/22x22/actions/journal-new.svg, Numix/24x24/actions/journal-new.svg, Numix/256x256/actions/journal-new.svg, Numix/32x32/actions/journal-new.svg, Numix/48x48/actions/journal-new.svg, Numix/64x64/actions/journal-new.svg
=> Symlinks for journal-new

Numix/16x16/devices/battery.svg, Numix/22x22/devices/battery.svg, Numix/24x24/devices/battery.svg, Numix/32x32/devices/battery-caution-charging.svg, Numix/32x32/devices/battery-caution.svg, Numix/32x32/devices/battery-empty-charging.svg, Numix/32x32/devices/battery-empty.svg, Numix/32x32/devices/battery-full-charging.svg, Numix/32x32/devices/battery-good-charging.svg, Numix/32x32/devices/battery-good.svg, Numix/32x32/devices/battery-low-charging.svg, Numix/32x32/devices/battery-low.svg, Numix/32x32/devices/battery-missing.svg, Numix/32x32/devices/battery.svg, Numix/48x48/devices/battery-caution-charging.svg, Numix/48x48/devices/battery-caution.svg, Numix/48x48/devices/battery-empty-charging.svg, Numix/48x48/devices/battery-empty.svg, Numix/48x48/devices/battery-full-charging.svg, Numix/48x48/devices/battery-good-charging.svg, Numix/48x48/devices/battery-good.svg, Numix/48x48/devices/battery-low-charging.svg, Numix/48x48/devices/battery-low.svg, Numix/48x48/devices/battery-missing.svg, Numix/48x48/devices/battery.svg
Fixed alignment of battery icons in `devices`
=> Alignment issues for battery icons in devices

Numix/48x48/notifications/notification-device-eject.svg, Numix/48x48/notifications/notification-disabled.svg, Numix/48x48/notifications/notification-display-brightness.svg, Numix/48x48/notifications/notification-power.svg, Numix/48x48/notifications/notification-wifi-enabled.svg
Several icons from #437. A lot of the notification icons over there are actually already present in Numix
=> Adds several notification icons

Numix/16x16/devices/audio-input-microphone.svg, Numix/22x22/devices/audio-input-microphone.svg, Numix/24x24/devices/audio-input-microphone.svg, Numix/32x32/devices/audio-input-microphone.svg, Numix/48x48/devices/audio-input-microphone.svg
=> Adds new design for audio-input-microphone

Numix/16x16/devices/audio-headphones.svg, Numix/16x16/devices/audio-headset.svg, Numix/22x22/devices/audio-headphones.svg, Numix/22x22/devices/audio-headset.svg, Numix/24x24/devices/audio-headphones.svg, Numix/24x24/devices/audio-headset.svg, Numix/32x32/devices/audio-headphones.svg, Numix/32x32/devices/audio-headset.svg, Numix/48x48/devices/audio-headphones.svg, Numix/48x48/devices/audio-headset.svg
from #727 I added different icons for headset and headphones (although very similar)
=> Adds new design for audio-headphone/headset

Numix/16x16/devices/phone.svg, Numix/22x22/devices/phone.svg, Numix/24x24/devices/phone.svg, Numix/32x32/devices/phone.svg
=> Adds new phone design for smaller sizes

Numix/16x16/devices/mouse.svg, Numix/22x22/devices/mouse.svg, Numix/24x24/devices/mouse.svg, Numix/32x32/devices/mouse.svg
=> Adds mouse icon for smaller sizes

Numix/16x16/devices/camera-web.svg, Numix/22x22/devices/camera-web.svg, Numix/24x24/devices/camera-web.svg, Numix/32x32/devices/camera-web.svg, Numix/48x48/devices/camera-web.svg
=> Adds camera-web for smaller sizes, cleans size 48

Numix/128x128/actions/games-endturn.svg, Numix/128x128/actions/go-jump-today.svg, Numix/128x128/actions/view-task.svg, Numix/16x16/actions/games-endturn.svg, Numix/16x16/actions/go-jump-today.svg, Numix/16x16/actions/view-task.svg, Numix/22x22/actions/games-endturn.svg, Numix/22x22/actions/go-jump-today.svg, Numix/22x22/actions/view-task.svg, Numix/24x24/actions/games-endturn.svg, Numix/24x24/actions/go-jump-today.svg, Numix/24x24/actions/view-task.svg, Numix/256x256/actions/games-endturn.svg, Numix/256x256/actions/go-jump-today.svg, Numix/256x256/actions/view-task.svg, Numix/32x32/actions/games-endturn.svg, Numix/32x32/actions/go-jump-today.svg, Numix/32x32/actions/view-task.svg, Numix/48x48/actions/games-endturn.svg, Numix/48x48/actions/go-jump-today.svg, Numix/48x48/actions/view-task.svg, Numix/64x64/actions/games-endturn.svg, Numix/64x64/actions/go-jump-today.svg, Numix/64x64/actions/view-task.svg
From #580:
``games-endturn``
``go-jump-today``
``view-task``
=> Symlinks for some more Oxygen/Breeze action icons

Numix/128x128/actions/transform-scale.svg, Numix/16x16/actions/transform-scale.svg, Numix/22x22/actions/transform-scale.svg, Numix/24x24/actions/transform-scale.svg, Numix/256x256/actions/transform-scale.svg, Numix/32x32/actions/transform-scale.svg, Numix/48x48/actions/transform-scale.svg, Numix/64x64/actions/transform-scale.svg
=> Added transform-scale action icon

Numix/128x128/actions/zoom-fit-height.svg, Numix/128x128/actions/zoom-fit-width.svg, Numix/16x16/actions/zoom-fit-height.svg, Numix/16x16/actions/zoom-fit-width.svg, Numix/22x22/actions/zoom-fit-height.svg, Numix/22x22/actions/zoom-fit-width.svg, Numix/24x24/actions/zoom-fit-height.svg, Numix/24x24/actions/zoom-fit-width.svg, Numix/256x256/actions/zoom-fit-height.svg, Numix/256x256/actions/zoom-fit-width.svg, Numix/32x32/actions/zoom-fit-height.svg, Numix/32x32/actions/zoom-fit-width.svg, Numix/48x48/actions/zoom-fit-height.svg, Numix/48x48/actions/zoom-fit-width.svg, Numix/64x64/actions/zoom-fit-height.svg, Numix/64x64/actions/zoom-fit-width.svg
=> Added zoom-fit-height and zoom-fit-width action icons

Numix-Light/16x16/status/intel-panel.svg, Numix-Light/16x16/status/nvidia-panel.svg, Numix-Light/22x22/status/intel-panel.svg, Numix-Light/22x22/status/nvidia-panel.svg, Numix-Light/24x24/status/intel-panel.svg, Numix-Light/24x24/status/nvidia-panel.svg, Numix/16x16/status/intel-panel.svg, Numix/16x16/status/nvidia-panel.svg, Numix/22x22/status/intel-panel.svg, Numix/22x22/status/nvidia-panel.svg, Numix/24x24/status/intel-panel.svg, Numix/24x24/status/nvidia-panel.svg
Used by the prime indicator for switching between intel and nvidia graphic cards
=> Adds intel-panel.svg icon / symlink for nvidia-panel

Numix/128x128/mimetypes/text-x-go.svg, Numix/16x16/mimetypes/text-x-go.svg, Numix/22x22/mimetypes/text-x-go.svg, Numix/24x24/mimetypes/text-x-go.svg, Numix/256x256/mimetypes/text-x-go.svg, Numix/32x32/mimetypes/text-x-go.svg, Numix/48x48/mimetypes/text-x-go.svg, Numix/64x64/mimetypes/text-x-go.svg
=> Mimetype icons for Go source files

Numix/128x128/mimetypes/application-x-gzpostscript.svg, Numix/16x16/mimetypes/application-x-gzpostscript.svg, Numix/22x22/mimetypes/application-x-gzpostscript.svg, Numix/24x24/mimetypes/application-x-gzpostscript.svg, Numix/256x256/mimetypes/application-x-gzpostscript.svg, Numix/32x32/mimetypes/application-x-gzpostscript.svg, Numix/48x48/mimetypes/application-x-gzpostscript.svg, Numix/64x64/mimetypes/application-x-gzpostscript.svg
=> Symlinks for application-x-gzpostscript mimetype

Numix/16x16/devices/media-tape.svg, Numix/22x22/devices/media-tape.svg, Numix/24x24/devices/media-tape.svg, Numix/32x32/devices/media-tape.svg, Numix/48x48/devices/media-tape.svg
=> Adds new design for media-tape.svg

Numix/16x16/devices/gnome-dev-memory.svg, Numix/22x22/devices/gnome-dev-memory.svg, Numix/24x24/devices/gnome-dev-memory.svg, Numix/32x32/devices/gnome-dev-memory.svg, Numix/48x48/devices/gnome-dev-memory.svg
=> Adds new design for gnome-dev-memory for smaller sizes

Numix/128x128/mimetypes/message.svg, Numix/16x16/mimetypes/message.svg, Numix/22x22/mimetypes/message.svg, Numix/24x24/mimetypes/message.svg, Numix/256x256/mimetypes/message.svg, Numix/32x32/mimetypes/message.svg, Numix/48x48/mimetypes/message.svg, Numix/64x64/mimetypes/message.svg
=> Symlinks for message mimetype

Numix/128x128/actions/tools-wizard.svg, Numix/16x16/actions/tools-wizard.svg, Numix/22x22/actions/tools-wizard.svg, Numix/24x24/actions/tools-wizard.svg, Numix/256x256/actions/tools-wizard.svg, Numix/32x32/actions/tools-wizard.svg, Numix/48x48/actions/tools-wizard.svg, Numix/64x64/actions/tools-wizard.svg
=> Symlinks for tools-wizard action icon

Numix/128x128/actions/mail-message.svg, Numix/16x16/actions/mail-message.svg, Numix/22x22/actions/mail-message.svg, Numix/24x24/actions/mail-message.svg, Numix/256x256/actions/mail-message.svg, Numix/32x32/actions/mail-message.svg, Numix/48x48/actions/mail-message.svg, Numix/64x64/actions/mail-message.svg
=> mail-message  action icon

Numix/128x128/actions/mail-encrypted.svg, Numix/16x16/actions/mail-encrypted.svg, Numix/22x22/actions/mail-encrypted.svg, Numix/24x24/actions/mail-encrypted.svg, Numix/256x256/actions/mail-encrypted.svg, Numix/32x32/actions/mail-encrypted.svg, Numix/48x48/actions/mail-encrypted.svg, Numix/64x64/actions/mail-encrypted.svg
From #580.
9th changed file is alignment correction.
=> mail-encrypted action icon

Numix/16x16/devices/drive-removable-media-usb.svg, Numix/22x22/devices/drive-removable-media-usb.svg, Numix/24x24/devices/drive-removable-media-usb.svg, Numix/32x32/devices/drive-removable-media-usb.svg, Numix/48x48/devices/drive-removable-media-usb.svg
Small alignment fixes for drive-removable-media-usb
=> Alignment fixes for drive-removable-media-usb

Numix-Light/16x16/status/nm-signal-0-secure.svg, Numix-Light/22x22/status/nm-signal-0-secure.svg, Numix-Light/24x24/status/nm-signal-0-secure.svg, Numix/16x16/status/nm-signal-0-secure.svg, Numix/22x22/status/nm-signal-0-secure.svg, Numix/24x24/status/nm-signal-0-secure.svg, Numix/48x48/notifications/notification-network-wired.svg, Numix/48x48/notifications/notification-network-wireless.svg
=> Symlinks for elementary

Numix/128x128/actions/merge.svg, Numix/128x128/actions/object-merge.svg, Numix/128x128/actions/split.svg, Numix/16x16/actions/merge.svg, Numix/16x16/actions/object-merge.svg, Numix/16x16/actions/split.svg, Numix/22x22/actions/merge.svg, Numix/22x22/actions/object-merge.svg, Numix/22x22/actions/split.svg, Numix/24x24/actions/merge.svg, Numix/24x24/actions/object-merge.svg, Numix/24x24/actions/split.svg, Numix/256x256/actions/merge.svg, Numix/256x256/actions/object-merge.svg, Numix/256x256/actions/split.svg, Numix/32x32/actions/merge.svg, Numix/32x32/actions/object-merge.svg, Numix/32x32/actions/split.svg, Numix/48x48/actions/merge.svg, Numix/48x48/actions/object-merge.svg, Numix/48x48/actions/split.svg, Numix/64x64/actions/merge.svg, Numix/64x64/actions/object-merge.svg, Numix/64x64/actions/split.svg
``merge`` and ``split`` from #580, ``object-merge`` from #437.
=> (object-)merge and split action icons

Numix/16/mimetypes/text-x-c++hdr.svg, Numix/16/mimetypes/text-x-chdr.svg, Numix/22/mimetypes/text-x-c++hdr.svg, Numix/24/mimetypes/text-x-c++hdr.svg, Numix/24/mimetypes/text-x-chdr.svg, Numix/32/mimetypes/text-x-c++hdr.svg, Numix/48/mimetypes/text-x-c++hdr.svg, Numix/48/mimetypes/text-x-chdr.svg, Numix/64/mimetypes/text-x-c++hdr.svg
Working on older issue reports. Fixes #263 . I inverted the colors of the source files (not quite but almost) in order to emphasize the difference between source and header files...
=> Adds text-x-chdr and text-x-c++hdr

Numix/16/devices/scanner.svg, Numix/22/devices/scanner.svg, Numix/24/devices/scanner.svg, Numix/32/devices/scanner.svg, Numix/48/devices/scanner.svg, Numix/64/devices/scanner.svg
=> Adds new design for scanner.svg

Numix/16/devices/input-gaming.svg, Numix/22/devices/input-gaming.svg, Numix/24/devices/input-gaming.svg, Numix/32/devices/input-gaming.svg, Numix/48/devices/input-gaming.svg, Numix/64/devices/input-gaming.svg
=> Adds input-gaming

Numix-Light/scalable/status/network-wireless-acquiring-symbolic.svg, Numix-Light/scalable/status/network-wireless-connected-symbolic.svg, Numix-Light/scalable/status/network-wireless-signal-none-symbolic.svg, Numix-Light/scalable/status/network-wireless-signal-ok-symbolic.svg, Numix-Light/scalable/status/network-wireless-signal-weak-symbolic.svg, Numix/scalable/status/network-wireless-acquiring-symbolic.svg, Numix/scalable/status/network-wireless-connected-symbolic.svg, Numix/scalable/status/network-wireless-signal-good-symbolic.svg, Numix/scalable/status/network-wireless-signal-none-symbolic.svg, Numix/scalable/status/network-wireless-signal-ok-symbolic.svg, Numix/scalable/status/network-wireless-signal-weak-symbolic.svg
New design for wifi scalable status icons
=> Adds new wifi design for scalable icons

Numix/16/actions/image-zoom-in.svg, Numix/16/actions/image-zoom-out.svg, Numix/22/actions/image-zoom-in.svg, Numix/22/actions/image-zoom-out.svg, Numix/24/actions/image-zoom-in.svg, Numix/24/actions/image-zoom-out.svg, Numix/32/actions/image-zoom-in.svg, Numix/32/actions/image-zoom-out.svg, Numix/48/actions/image-zoom-in.svg, Numix/48/actions/image-zoom-out.svg, Numix/64/actions/image-zoom-in.svg, Numix/64/actions/image-zoom-out.svg
``image-zoom-in`` and ``image-zoom-out`` from #580.
=> Added symlinks for image-zoom action icons

Numix/16/mimetypes/application-x-abiword.svg, Numix/22/mimetypes/application-x-abiword.svg, Numix/24/mimetypes/application-x-abiword.svg, Numix/32/mimetypes/application-x-abiword.svg, Numix/48/mimetypes/application-x-abiword.svg, Numix/64/mimetypes/application-x-abiword.svg
=> Added application-x-abiword mimetype

Numix/16/mimetypes/text-x-tcl.svg, Numix/22/mimetypes/text-x-tcl.svg, Numix/24/mimetypes/text-x-tcl.svg, Numix/32/mimetypes/text-x-tcl.svg, Numix/48/mimetypes/text-x-tcl.svg, Numix/64/mimetypes/text-x-tcl.svg
=> Added text-x-tcl mimetype

Numix/16/mimetypes/text-x-objchdr.svg, Numix/22/mimetypes/text-x-objchdr.svg, Numix/24/mimetypes/text-x-objchdr.svg, Numix/32/mimetypes/text-x-objchdr.svg, Numix/48/mimetypes/text-x-objchdr.svg, Numix/64/mimetypes/text-x-objchdr.svg
=> Added simlinks for Obj-C header mimetype

Numix/16/apps/goa-account-google.svg, Numix/22/apps/goa-account-google.svg, Numix/24/apps/goa-account-google.svg, Numix/32/apps/goa-account-google.svg, Numix/48/apps/goa-account-google.svg, Numix/64/apps/goa-account-google.svg
Well since google updated their icon the old "google-g" doesn't really fit anymore
=> Updates design of google-icon

Numix/16/mimetypes/application-x-k3b.svg, Numix/22/mimetypes/application-x-k3b.svg, Numix/24/mimetypes/application-x-k3b.svg, Numix/32/mimetypes/application-x-k3b.svg, Numix/48/mimetypes/application-x-k3b.svg, Numix/64/mimetypes/application-x-k3b.svg
=> Added symlinks for application-x-k3b mimetype

Numix/16/mimetypes/application-x-kexiproject-sqlite.svg, Numix/16/mimetypes/application-x-kexiproject-sqlite2.svg, Numix/16/mimetypes/application-x-kexiproject-sqlite3.svg, Numix/22/mimetypes/application-x-kexiproject-sqlite.svg, Numix/22/mimetypes/application-x-kexiproject-sqlite2.svg, Numix/22/mimetypes/application-x-kexiproject-sqlite3.svg, Numix/24/mimetypes/application-x-kexiproject-sqlite.svg, Numix/24/mimetypes/application-x-kexiproject-sqlite2.svg, Numix/24/mimetypes/application-x-kexiproject-sqlite3.svg, Numix/32/mimetypes/application-x-kexiproject-sqlite.svg, Numix/32/mimetypes/application-x-kexiproject-sqlite2.svg, Numix/32/mimetypes/application-x-kexiproject-sqlite3.svg, Numix/48/mimetypes/application-x-kexiproject-sqlite.svg, Numix/48/mimetypes/application-x-kexiproject-sqlite2.svg, Numix/48/mimetypes/application-x-kexiproject-sqlite3.svg, Numix/64/mimetypes/application-x-kexiproject-sqlite.svg, Numix/64/mimetypes/application-x-kexiproject-sqlite2.svg, Numix/64/mimetypes/application-x-kexiproject-sqlite3.svg
=> Added symlinks for application-x-kexiproject-sqlite* mimetypes

Numix/16/mimetypes/text-x-xslfo.svg, Numix/22/mimetypes/text-x-xslfo.svg, Numix/24/mimetypes/text-x-xslfo.svg, Numix/32/mimetypes/text-x-xslfo.svg, Numix/48/mimetypes/text-x-xslfo.svg, Numix/64/mimetypes/text-x-xslfo.svg
=> Symlinks for text-x-xlsfo mimetype

Numix/16/mimetypes/text-rdf+xml.svg, Numix/22/mimetypes/text-rdf+xml.svg, Numix/24/mimetypes/text-rdf+xml.svg, Numix/32/mimetypes/text-rdf+xml.svg, Numix/48/mimetypes/text-rdf+xml.svg, Numix/64/mimetypes/text-rdf+xml.svg
=> Symlinks for text-rdf+xml mimetype

Numix/16/mimetypes/image-vnd.adobe.photoshop.svg, Numix/22/mimetypes/image-vnd.adobe.photoshop.svg, Numix/24/mimetypes/image-vnd.adobe.photoshop.svg, Numix/32/mimetypes/image-vnd.adobe.photoshop.svg, Numix/48/mimetypes/image-vnd.adobe.photoshop.svg, Numix/64/mimetypes/image-vnd.adobe.photoshop.svg
=> Symlinks for image-vnd.adobe.photoshop mimetype

Numix/16/actions/view-grid.svg, Numix/16/actions/view-list.svg, Numix/22/actions/view-grid.svg, Numix/22/actions/view-list.svg, Numix/24/actions/view-grid.svg, Numix/24/actions/view-list.svg, Numix/32/actions/view-grid.svg, Numix/32/actions/view-list.svg, Numix/48/actions/view-grid.svg, Numix/48/actions/view-list.svg, Numix/64/actions/view-grid.svg, Numix/64/actions/view-list.svg
=> view-grid and view-list action icons

Numix/16/actions/gtk-bold.svg, Numix/22/actions/gtk-bold.svg, Numix/24/actions/gtk-bold.svg, Numix/32/actions/gtk-bold.svg, Numix/48/actions/gtk-bold.svg, Numix/64/actions/gtk-bold.svg
=> Symlinks for gtk-bold

Numix/index.theme
Because the places folders are special
=> Small fix to index.theme

Numix/16/actions/games-difficult.svg, Numix/16/actions/games-hint.svg, Numix/16/actions/games-solve.svg, Numix/22/actions/games-difficult.svg, Numix/22/actions/games-hint.svg, Numix/22/actions/games-solve.svg, Numix/24/actions/games-difficult.svg, Numix/24/actions/games-hint.svg, Numix/24/actions/games-solve.svg, Numix/32/actions/games-difficult.svg, Numix/32/actions/games-hint.svg, Numix/32/actions/games-solve.svg, Numix/48/actions/games-difficult.svg, Numix/48/actions/games-hint.svg, Numix/48/actions/games-solve.svg, Numix/64/actions/games-difficult.svg, Numix/64/actions/games-hint.svg, Numix/64/actions/games-solve.svg
From #580:
+ games-difficult
+ games-hint
+ games-solve
=> Some action icons for KDE games

Numix/16/mimetypes/application-x-keepass2.svg, Numix/22/mimetypes/application-x-keepass2.svg, Numix/24/mimetypes/application-x-keepass2.svg, Numix/32/mimetypes/application-x-keepass2.svg, Numix/48/mimetypes/application-x-keepass2.svg, Numix/64/mimetypes/application-x-keepass2.svg
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/2650.
=> Symlinks for application/x-keepass2

Numix/128/places/folder-books.svg, Numix/16/places/folder-books.svg, Numix/22/places/folder-books.svg, Numix/24/places/folder-books.svg, Numix/256/places/folder-books.svg, Numix/32/places/folder-books.svg, Numix/48/places/folder-books.svg, Numix/64/places/folder-books.svg, Numix/96/places/folder-books.svg, Numix/96/places/start-here.svg
Symlinks for folder-books. I also changed the size for start-here in 96px because it was a 48px icon
=> Adds symlink for folder-books.svg

Numix-Light/16/status/wiznote-indicator.svg, Numix-Light/22/status/wiznote-indicator.svg, Numix-Light/24/status/wiznote-indicator.svg, Numix/16/status/wiznote-indicator.svg, Numix/22/status/wiznote-indicator.svg, Numix/24/status/wiznote-indicator.svg
=> Adds wiznote-indicator

Numix/16/actions/edit-clear-all.svg, Numix/22/actions/edit-clear-all.svg, Numix/24/actions/edit-clear-all.svg, Numix/32/actions/edit-clear-all.svg, Numix/48/actions/edit-clear-all.svg, Numix/64/actions/edit-clear-all.svg
This icon is used in Latexilla(LaTex editor)
=> create a symlink for edit-clear-all

Numix/16/actions/bp-toggle.svg, Numix/16/actions/db-cont.svg, Numix/16/actions/db-stop.svg, Numix/22/actions/bp-toggle.svg, Numix/22/actions/db-cont.svg, Numix/22/actions/db-stop.svg, Numix/24/actions/bp-toggle.svg, Numix/24/actions/db-cont.svg, Numix/24/actions/db-stop.svg, Numix/32/actions/bp-toggle.svg, Numix/32/actions/db-cont.svg, Numix/32/actions/db-stop.svg, Numix/48/actions/bp-toggle.svg, Numix/48/actions/db-cont.svg, Numix/48/actions/db-stop.svg, Numix/64/actions/bp-toggle.svg, Numix/64/actions/db-cont.svg, Numix/64/actions/db-stop.svg
=> few symlinks for octave

Numix/16/actions/bold.svg, Numix/16/actions/italic.svg, Numix/16/actions/table.svg, Numix/16/actions/underline.svg, Numix/22/actions/bold.svg, Numix/22/actions/italic.svg, Numix/22/actions/table.svg, Numix/22/actions/underline.svg, Numix/24/actions/bold.svg, Numix/24/actions/italic.svg, Numix/24/actions/table.svg, Numix/24/actions/underline.svg, Numix/32/actions/bold.svg, Numix/32/actions/italic.svg, Numix/32/actions/table.svg, Numix/32/actions/underline.svg, Numix/48/actions/bold.svg, Numix/48/actions/italic.svg, Numix/48/actions/table.svg, Numix/48/actions/underline.svg, Numix/64/actions/bold.svg, Numix/64/actions/italic.svg, Numix/64/actions/table.svg, Numix/64/actions/underline.svg
#871 
Symlinks : 
- table
- bold
- italic
- underline
=> few symlinks for latexila

Numix/16/actions/chronometer.svg, Numix/22/actions/chronometer.svg, Numix/24/actions/chronometer.svg, Numix/32/actions/chronometer.svg, Numix/48/actions/chronometer.svg, Numix/64/actions/chronometer.svg
=> chronometer action icon

Numix/16/actions/view-statistics.svg, Numix/22/actions/view-statistics.svg, Numix/24/actions/view-statistics.svg, Numix/32/actions/view-statistics.svg, Numix/48/actions/view-statistics.svg, Numix/64/actions/view-statistics.svg
=> Symlinks for view-statistics action

Numix/16/actions/list-itemize.svg, Numix/22/actions/list-itemize.svg, Numix/24/actions/list-itemize.svg, Numix/32/actions/list-itemize.svg, Numix/48/actions/list-itemize.svg, Numix/64/actions/list-itemize.svg
#871 
- list-itemize -> view-list
=> an other symlink for latexila

Numix/16/actions/invertimage.svg, Numix/22/actions/invertimage.svg, Numix/24/actions/invertimage.svg, Numix/32/actions/invertimage.svg, Numix/48/actions/invertimage.svg, Numix/64/actions/invertimage.svg
=> Symlinks for invertimage action

Numix/16/actions/edit-clear-locationbar-rtl.svg, Numix/22/actions/edit-clear-locationbar-rtl.svg, Numix/24/actions/edit-clear-locationbar-rtl.svg, Numix/32/actions/edit-clear-locationbar-rtl.svg, Numix/48/actions/edit-clear-locationbar-rtl.svg, Numix/64/actions/edit-clear-locationbar-rtl.svg
=> Adds edit-clear-locationbar-rtl

Numix/16/actions/korg-todo.svg, Numix/16/actions/x-clementine-shuffle.svg, Numix/22/actions/korg-todo.svg, Numix/22/actions/x-clementine-shuffle.svg, Numix/24/actions/korg-todo.svg, Numix/24/actions/x-clementine-shuffle.svg, Numix/32/actions/korg-todo.svg, Numix/32/actions/x-clementine-shuffle.svg, Numix/48/actions/korg-todo.svg, Numix/48/actions/x-clementine-shuffle.svg, Numix/64/actions/korg-todo.svg, Numix/64/actions/x-clementine-shuffle.svg
2 from #580.
Action icons for Korganizer and Clementine.
=> Symlinks for korg-todo and x-clementine-shuffle

Numix/16/actions/chronometer-lap.svg, Numix/16/actions/chronometer-pause.svg, Numix/16/actions/chronometer-reset.svg, Numix/16/actions/chronometer-start.svg, Numix/22/actions/chronometer-lap.svg, Numix/22/actions/chronometer-pause.svg, Numix/22/actions/chronometer-reset.svg, Numix/22/actions/chronometer-start.svg, Numix/24/actions/chronometer-lap.svg, Numix/24/actions/chronometer-pause.svg, Numix/24/actions/chronometer-reset.svg, Numix/24/actions/chronometer-start.svg, Numix/32/actions/chronometer-lap.svg, Numix/32/actions/chronometer-pause.svg, Numix/32/actions/chronometer-reset.svg, Numix/32/actions/chronometer-start.svg, Numix/48/actions/chronometer-lap.svg, Numix/48/actions/chronometer-pause.svg, Numix/48/actions/chronometer-reset.svg, Numix/48/actions/chronometer-start.svg, Numix/64/actions/chronometer-lap.svg, Numix/64/actions/chronometer-pause.svg, Numix/64/actions/chronometer-reset.svg, Numix/64/actions/chronometer-start.svg
=> More chronometer action icons

Numix/16/actions/action-unavailable.svg, Numix/16/actions/edit-clear-all.svg, Numix/16/actions/view-wrapped.svg, Numix/22/actions/action-unavailable.svg, Numix/22/actions/edit-clear-all.svg, Numix/22/actions/view-wrapped.svg, Numix/24/actions/action-unavailable.svg, Numix/24/actions/edit-clear-all.svg, Numix/24/actions/view-wrapped.svg, Numix/32/actions/action-unavailable.svg, Numix/32/actions/edit-clear-all.svg, Numix/32/actions/view-wrapped.svg, Numix/48/actions/action-unavailable.svg, Numix/48/actions/edit-clear-all.svg, Numix/48/actions/view-wrapped.svg, Numix/64/actions/action-unavailable.svg, Numix/64/actions/edit-clear-all.svg, Numix/64/actions/view-wrapped.svg
From #827 
+ action-unavailable
+ edit-clear-all
+ view-wrapped
=> Symlinks for HighContrast

Numix/16/status/changes-allow.svg, Numix/16/status/changes-prevent.svg
=> Bigger 16px changes-allow/prevent

Numix/16/status/lock.svg, Numix/16/status/unlock.svg, Numix/22/status/lock.svg, Numix/22/status/unlock.svg, Numix/24/status/lock.svg, Numix/24/status/unlock.svg, Numix/32/status/lock.svg, Numix/32/status/unlock.svg, Numix/48/status/lock.svg, Numix/48/status/unlock.svg, Numix/64/status/lock.svg, Numix/64/status/unlock.svg
=> Symlinks for lock and unlock

Numix/16/actions/find-location.svg, Numix/16/actions/send-to.svg, Numix/16/status/channel-secure.svg, Numix/22/actions/find-location.svg, Numix/22/actions/send-to.svg, Numix/22/status/channel-secure.svg, Numix/24/actions/find-location.svg, Numix/24/actions/send-to.svg, Numix/24/status/channel-secure.svg, Numix/32/actions/find-location.svg, Numix/32/actions/send-to.svg, Numix/32/status/channel-secure.svg, Numix/48/actions/find-location.svg, Numix/48/actions/send-to.svg, Numix/48/status/channel-secure.svg, Numix/64/actions/find-location.svg, Numix/64/actions/send-to.svg, Numix/64/status/channel-secure.svg
Few symlinks #827 
- find-location
- send-to
- channel-secure
=> some symlinks for highcontrast

Numix-Light/scalable/actions/close-symbolic.svg, Numix-Light/scalable/actions/format-text-remove-symbolic.svg, Numix/scalable/actions/close-symbolic.svg, Numix/scalable/actions/format-text-remove-symbolic.svg
#768  
- close-symbolic
- format-text-remove-symbolic
=> two symlinks for geary

Numix/16/mimetypes/application-x-scilab.svg, Numix/22/mimetypes/application-x-scilab.svg, Numix/24/mimetypes/application-x-scilab.svg, Numix/32/mimetypes/application-x-scilab.svg, Numix/48/mimetypes/application-x-scilab.svg, Numix/64/mimetypes/application-x-scilab.svg
Taken from numix circle icon. Part of #840
=> Scilab filetype icon

Numix/16/mimetypes/text-x-opml.svg, Numix/22/mimetypes/text-x-opml.svg, Numix/24/mimetypes/text-x-opml.svg, Numix/32/mimetypes/text-x-opml.svg, Numix/48/mimetypes/text-x-opml.svg, Numix/64/mimetypes/text-x-opml.svg
=> Symlinks for text-x-opml

Numix/16/mimetypes/application-x-musescore.svg, Numix/22/mimetypes/application-x-musescore.svg, Numix/24/mimetypes/application-x-musescore.svg, Numix/32/mimetypes/application-x-musescore.svg, Numix/48/mimetypes/application-x-musescore.svg, Numix/64/mimetypes/application-x-musescore.svg
=> Symlinks for application-x-musescore

Numix/32/mimetypes/application-x-python-bytecode.svg, Numix/64/mimetypes/application-x-python-bytecode.svg
=> Alignment fix for application-x-python-bytecode

Numix/16/mimetypes/application-x-gambas3.svg, Numix/22/mimetypes/application-x-gambas3.svg, Numix/24/mimetypes/application-x-gambas3.svg, Numix/32/mimetypes/application-x-gambas3.svg, Numix/48/mimetypes/application-x-gambas3.svg, Numix/64/mimetypes/application-x-gambas3.svg
=> Gambas mimetype

Numix/16/mimetypes/application-x-shared-library-la.svg, Numix/16/mimetypes/application-x-sharedlib.svg, Numix/22/mimetypes/application-x-shared-library-la.svg, Numix/22/mimetypes/application-x-sharedlib.svg, Numix/24/mimetypes/application-x-shared-library-la.svg, Numix/24/mimetypes/application-x-sharedlib.svg, Numix/32/mimetypes/application-x-shared-library-la.svg, Numix/32/mimetypes/application-x-sharedlib.svg, Numix/48/mimetypes/application-x-shared-library-la.svg, Numix/48/mimetypes/application-x-sharedlib.svg, Numix/64/mimetypes/application-x-shared-library-la.svg, Numix/64/mimetypes/application-x-sharedlib.svg
Fixes #557 #559 
**Alternatives:**
22/24:
16:
**Description:** The design idea came from [here](https://github.com/hlechner/hl-numix-mime/issues/6).
=> sharedlib mimetype - Fixes #557 #559

Numix/16/mimetypes/application-x-riff.svg, Numix/22/mimetypes/application-x-riff.svg, Numix/24/mimetypes/application-x-riff.svg, Numix/32/mimetypes/application-x-riff.svg, Numix/48/mimetypes/application-x-riff.svg, Numix/64/mimetypes/application-x-riff.svg
RIFF mimetype #898
Further details: [here](https://github.com/hlechner/hl-numix-mime/issues/1)
=> RIFF mimetype

Numix/16/mimetypes/application-x-mswinurl.svg, Numix/22/mimetypes/application-x-mswinurl.svg, Numix/24/mimetypes/application-x-mswinurl.svg, Numix/32/mimetypes/application-x-mswinurl.svg, Numix/48/mimetypes/application-x-mswinurl.svg, Numix/64/mimetypes/application-x-mswinurl.svg
MSWINURL mimetype #898 
Further details: [here](https://github.com/hlechner/hl-numix-mime/issues/1)
=> MSURL mimetype

Numix/16/actions/db-step-in.svg, Numix/16/actions/db-step-out.svg, Numix/16/actions/db-step.svg, Numix/22/actions/db-step-in.svg, Numix/22/actions/db-step-out.svg, Numix/22/actions/db-step.svg, Numix/24/actions/db-step-in.svg, Numix/24/actions/db-step-out.svg, Numix/24/actions/db-step.svg, Numix/32/actions/db-step-in.svg, Numix/32/actions/db-step-out.svg, Numix/32/actions/db-step.svg, Numix/48/actions/db-step-in.svg, Numix/48/actions/db-step-out.svg, Numix/48/actions/db-step.svg, Numix/64/actions/db-step-in.svg, Numix/64/actions/db-step-out.svg, Numix/64/actions/db-step.svg
All ``db-step-*`` icons from #870, preview over there.
=> db-step-* action icons for Octave

Numix-Light/scalable/categories/applications-education-symbolic.svg, Numix-Light/scalable/categories/applications-engineering-symbolic.svg, Numix-Light/scalable/categories/applications-games-symbolic.svg, Numix-Light/scalable/categories/applications-graphics-symbolic.svg, Numix-Light/scalable/categories/applications-internet-symbolic.svg, Numix-Light/scalable/categories/applications-multimedia-symbolic.svg, Numix-Light/scalable/categories/applications-science-symbolic.svg, Numix-Light/scalable/categories/applications-utilities-symbolic.svg, Numix-Light/scalable/categories/event-birthday-symbolic.svg, Numix-Light/scalable/categories/preferences-desktop-accessibility-symbolic.svg, Numix-Light/scalable/categories/system-help-symbolic.svg, Numix/scalable/categories/applications-education-symbolic.svg, Numix/scalable/categories/applications-engineering-symbolic.svg, Numix/scalable/categories/applications-games-symbolic.svg, Numix/scalable/categories/applications-graphics-symbolic.svg, Numix/scalable/categories/applications-internet-symbolic.svg, Numix/scalable/categories/applications-multimedia-symbolic.svg, Numix/scalable/categories/applications-science-symbolic.svg, Numix/scalable/categories/applications-utilities-symbolic.svg, Numix/scalable/categories/event-birthday-symbolic.svg, Numix/scalable/categories/preferences-desktop-accessibility-symbolic.svg, Numix/scalable/categories/system-help-symbolic.svg
Bunch of scalable categories icons. I shamelessly copied one icon from elementary theme since it was already pretty enough (birhtday icon), the other icons I used already existig desings from Numix
From: #437
=> Adds bunch of scalable categories icons

Numix-Light/scalable/actions/edit-paste-symbolic.svg, Numix/scalable/actions/edit-paste-symbolic.svg
=> New design for edit-paste-symbolic

Numix/16/actions/bp-next.svg, Numix/16/actions/bp-prev.svg, Numix/16/actions/bp-rm-all.svg, Numix/16/actions/bp-toggle.svg, Numix/22/actions/bp-next.svg, Numix/22/actions/bp-prev.svg, Numix/22/actions/bp-rm-all.svg, Numix/22/actions/bp-toggle.svg, Numix/24/actions/bp-next.svg, Numix/24/actions/bp-prev.svg, Numix/24/actions/bp-rm-all.svg, Numix/24/actions/bp-toggle.svg, Numix/32/actions/bp-next.svg, Numix/32/actions/bp-prev.svg, Numix/32/actions/bp-rm-all.svg, Numix/32/actions/bp-toggle.svg, Numix/48/actions/bp-next.svg, Numix/48/actions/bp-prev.svg, Numix/48/actions/bp-rm-all.svg, Numix/48/actions/bp-toggle.svg, Numix/64/actions/bp-next.svg, Numix/64/actions/bp-prev.svg, Numix/64/actions/bp-rm-all.svg, Numix/64/actions/bp-toggle.svg
All ``bp-*`` icons from #870, preview over there.
=> Breakpoint action icons for Octave

Numix/16/apps/ppa.svg, Numix/16/devices/processor.svg, Numix/22/apps/ppa.svg, Numix/22/devices/processor.svg, Numix/24/apps/ppa.svg, Numix/24/devices/processor.svg, Numix/32/apps/ppa.svg, Numix/32/devices/processor.svg, Numix/48/apps/ppa.svg, Numix/48/devices/processor.svg, Numix/64/apps/ppa.svg, Numix/64/devices/processor.svg
Two new icons from elementary-theme. #437
=> Adds two icons from elementary theme

Numix/16/mimetypes/video-x-flv.svg, Numix/22/mimetypes/video-x-flv.svg, Numix/24/mimetypes/video-x-flv.svg, Numix/32/mimetypes/video-x-flv.svg, Numix/48/mimetypes/video-x-flv.svg, Numix/64/mimetypes/video-x-flv.svg
=> Symlinks for FLV mimetype

Numix/16/devices/cpu.svg, Numix/16/devices/device_cpu.svg, Numix/22/devices/cpu.svg, Numix/22/devices/device_cpu.svg, Numix/24/devices/cpu.svg, Numix/24/devices/device_cpu.svg, Numix/32/devices/cpu.svg, Numix/32/devices/device_cpu.svg, Numix/48/devices/cpu.svg, Numix/48/devices/device_cpu.svg, Numix/64/devices/cpu.svg, Numix/64/devices/device_cpu.svg
``cpu`` from #580.
``device_cpu`` from #124.
=> CPU device symlinks

Numix/16/mimetypes/application-x-amiga-disk-format.svg, Numix/22/mimetypes/application-x-amiga-disk-format.svg, Numix/24/mimetypes/application-x-amiga-disk-format.svg, Numix/32/mimetypes/application-x-amiga-disk-format.svg, Numix/48/mimetypes/application-x-amiga-disk-format.svg, Numix/64/mimetypes/application-x-amiga-disk-format.svg
=> amiga disk mimetype

Numix/16/status/security-high.svg, Numix/16/status/security-low.svg, Numix/16/status/security-medium.svg, Numix/22/status/security-high.svg, Numix/22/status/security-low.svg, Numix/22/status/security-medium.svg, Numix/24/status/security-high.svg, Numix/24/status/security-low.svg, Numix/24/status/security-medium.svg, Numix/32/status/security-high.svg, Numix/32/status/security-low.svg, Numix/32/status/security-medium.svg, Numix/48/status/security-high.svg, Numix/48/status/security-low.svg, Numix/48/status/security-medium.svg, Numix/64/status/security-high.svg, Numix/64/status/security-low.svg, Numix/64/status/security-medium.svg
=> Adds security-* icons

Numix/16/mimetypes/application-x-ole-storage.svg, Numix/22/mimetypes/application-x-ole-storage.svg, Numix/24/mimetypes/application-x-ole-storage.svg, Numix/32/mimetypes/application-x-ole-storage.svg, Numix/48/mimetypes/application-x-ole-storage.svg, Numix/64/mimetypes/application-x-ole-storage.svg
Similar idea of RIFF file #920 
**OLE2 compound document storage** (application/x-ole-storage)
> Object Linking and Embedding (OLE, sometimes pronounced /oˈlɛj/) is a proprietary technology developed by Microsoft that allows embedding and linking to documents and other objects. For developers, it brought OLE Control Extension (OCX), a way to develop and use custom user interface elements. On a technical level, an OLE object is any object that implements the IOleObject interface, possibly along with a wide range of other interfaces, depending on the object's needs.
Other Microsoft format similar to container-file like RIFF.
=> OLE symlink changed

Numix/16/mimetypes/text-x-scala.svg, Numix/22/mimetypes/text-x-scala.svg, Numix/24/mimetypes/text-x-scala.svg, Numix/32/mimetypes/text-x-scala.svg, Numix/48/mimetypes/text-x-scala.svg, Numix/64/mimetypes/text-x-scala.svg
=> Scala mimetype

Numix/16/mimetypes/application-x-sharedlib.svg, Numix/22/mimetypes/application-x-sharedlib.svg, Numix/24/mimetypes/application-x-sharedlib.svg, Numix/32/mimetypes/application-x-sharedlib.svg, Numix/48/mimetypes/application-x-sharedlib.svg, Numix/64/mimetypes/application-x-sharedlib.svg
=> LIB mime - fix the icons to guideline

Numix/16/status/user-idle.svg, Numix/16/status/user-typing.svg, Numix/16/status/view-private.svg, Numix/22/status/user-idle.svg, Numix/22/status/user-typing.svg, Numix/22/status/view-private.svg, Numix/24/status/user-idle.svg, Numix/24/status/user-typing.svg, Numix/24/status/view-private.svg, Numix/32/status/view-private.svg, Numix/48/status/view-private.svg, Numix/64/status/view-private.svg
Two new icons and a symlink for #437
=> Three new icons for elementary

Numix/16/mimetypes/application-vnd.geogebra.file.svg, Numix/22/mimetypes/application-vnd.geogebra.file.svg, Numix/24/mimetypes/application-vnd.geogebra.file.svg, Numix/32/mimetypes/application-vnd.geogebra.file.svg, Numix/48/mimetypes/application-vnd.geogebra.file.svg, Numix/64/mimetypes/application-vnd.geogebra.file.svg
fixes #904 
Added mimetype: application/vnd.geogebra.file
=> fixes #904 (application/vnd.geogebra.file)

Numix/16/mimetypes/application-x-gnucash.svg, Numix/22/mimetypes/application-x-gnucash.svg, Numix/24/mimetypes/application-x-gnucash.svg, Numix/32/mimetypes/application-x-gnucash.svg, Numix/48/mimetypes/application-x-gnucash.svg, Numix/64/mimetypes/application-x-gnucash.svg
=> gnucash mimetype

Numix-Light/22/status/teamviewer-indicator-away.svg, Numix-Light/22/status/teamviewer-indicator-busy.svg, Numix-Light/22/status/teamviewer-indicator-connected.svg, Numix-Light/22/status/teamviewer-indicator-offline.svg, Numix-Light/22/status/teamviewer-indicator.svg, Numix-Light/24/status/teamviewer-indicator-away.svg, Numix-Light/24/status/teamviewer-indicator-busy.svg, Numix-Light/24/status/teamviewer-indicator-connected.svg, Numix-Light/24/status/teamviewer-indicator-offline.svg, Numix-Light/24/status/teamviewer-indicator.svg, Numix/22/status/teamviewer-indicator-away.svg, Numix/22/status/teamviewer-indicator-busy.svg, Numix/22/status/teamviewer-indicator-connected.svg, Numix/22/status/teamviewer-indicator-error.svg, Numix/22/status/teamviewer-indicator-offline.svg, Numix/22/status/teamviewer-indicator.svg, Numix/24/status/teamviewer-indicator-away.svg, Numix/24/status/teamviewer-indicator-busy.svg, Numix/24/status/teamviewer-indicator-connected.svg, Numix/24/status/teamviewer-indicator-error.svg, Numix/24/status/teamviewer-indicator-offline.svg, Numix/24/status/teamviewer-indicator.svg
The indicator was really big compared to already existing tray icons. Made the circle 1px smaller
=> Enhancement for teamviewer indicator

Numix/16/mimetypes/application-vnd.tcpdump.pcap.svg, Numix/22/mimetypes/application-vnd.tcpdump.pcap.svg, Numix/24/mimetypes/application-vnd.tcpdump.pcap.svg, Numix/32/mimetypes/application-vnd.tcpdump.pcap.svg, Numix/48/mimetypes/application-vnd.tcpdump.pcap.svg, Numix/64/mimetypes/application-vnd.tcpdump.pcap.svg
=> TCPDUMP mimetype

Numix/16/mimetypes/application-vnd.corel-draw.svg, Numix/16/mimetypes/image-cgm.svg, Numix/22/mimetypes/application-vnd.corel-draw.svg, Numix/22/mimetypes/image-cgm.svg, Numix/24/mimetypes/application-vnd.corel-draw.svg, Numix/24/mimetypes/image-cgm.svg, Numix/32/mimetypes/application-vnd.corel-draw.svg, Numix/32/mimetypes/image-cgm.svg, Numix/48/mimetypes/application-vnd.corel-draw.svg, Numix/48/mimetypes/image-cgm.svg, Numix/64/mimetypes/application-vnd.corel-draw.svg, Numix/64/mimetypes/image-cgm.svg
It's those two file formats:
https://en.wikipedia.org/wiki/Computer_Graphics_Metafile
http://whatis.techtarget.com/fileformat/CDR-Corel-Draw-Vector-drawing-file
I think the vector mime is a better fit than the default image one.
=> Symlinks for CGM and CGR image formats

Numix/16/actions/object-group.svg, Numix/16/actions/object-ungroup.svg, Numix/22/actions/object-group.svg, Numix/22/actions/object-ungroup.svg, Numix/24/actions/object-group.svg, Numix/24/actions/object-ungroup.svg, Numix/32/actions/object-group.svg, Numix/32/actions/object-ungroup.svg, Numix/48/actions/object-group.svg, Numix/48/actions/object-ungroup.svg, Numix/64/actions/object-group.svg, Numix/64/actions/object-ungroup.svg
=> Adds object-group.svg

Numix/16/mimetypes/application-x-addon.svg, Numix/22/mimetypes/application-x-addon.svg, Numix/24/mimetypes/application-x-addon.svg, Numix/32/mimetypes/application-x-addon.svg, Numix/48/mimetypes/application-x-addon.svg, Numix/64/mimetypes/application-x-addon.svg
=> Symlinks for application-x-addon

Numix-Light/16/status/wifi-020.svg, Numix-Light/16/status/wifi-040.svg, Numix-Light/16/status/wifi-060.svg, Numix-Light/16/status/wifi-080.svg, Numix-Light/22/status/wifi-020.svg, Numix-Light/22/status/wifi-040.svg, Numix-Light/22/status/wifi-060.svg, Numix-Light/22/status/wifi-080.svg, Numix-Light/24/status/wifi-020.svg, Numix-Light/24/status/wifi-040.svg, Numix-Light/24/status/wifi-060.svg, Numix-Light/24/status/wifi-080.svg, Numix/16/status/wifi-020.svg, Numix/16/status/wifi-040.svg, Numix/16/status/wifi-060.svg, Numix/16/status/wifi-080.svg, Numix/22/status/wifi-020.svg, Numix/22/status/wifi-040.svg, Numix/22/status/wifi-060.svg, Numix/22/status/wifi-080.svg, Numix/24/status/wifi-020.svg, Numix/24/status/wifi-040.svg, Numix/24/status/wifi-060.svg, Numix/24/status/wifi-080.svg
Add `wifi-*` icons from #826. The symlinks are the same as in `hicolor`
=> add wifi-* from Humanity

Numix/16/actions/lc_alignblock.svg, Numix/22/actions/lc_alignblock.svg, Numix/24/actions/lc_alignblock.svg, Numix/32/actions/lc_alignblock.svg, Numix/48/actions/lc_alignblock.svg, Numix/64/actions/lc_alignblock.svg
forgot one from #1038  in my previous PR
=> Adds lc_alignblock

Numix-Light/scalable/status/process-working-symbolic.svg, Numix/scalable/status/process-working-symbolic.svg
=> Adds process-working-symbolic

Numix/16/actions/media-import-audio-cd.svg, Numix/22/actions/media-import-audio-cd.svg, Numix/24/actions/media-import-audio-cd.svg, Numix/32/actions/media-import-audio-cd.svg, Numix/48/actions/media-import-audio-cd.svg, Numix/64/actions/media-import-audio-cd.svg
=> Adds media-import-audio-cd

Numix/16/actions/distribute-horizontal-gaps.svg, Numix/16/actions/distribute-vertical-gaps.svg, Numix/22/actions/distribute-horizontal-gaps.svg, Numix/22/actions/distribute-vertical-gaps.svg, Numix/24/actions/distribute-horizontal-gaps.svg, Numix/24/actions/distribute-vertical-gaps.svg, Numix/32/actions/distribute-horizontal-gaps.svg, Numix/32/actions/distribute-vertical-gaps.svg, Numix/48/actions/distribute-horizontal-gaps.svg, Numix/48/actions/distribute-vertical-gaps.svg, Numix/64/actions/distribute-horizontal-gaps.svg, Numix/64/actions/distribute-vertical-gaps.svg
two more icons for inkscape (the distribution icons are still mixed)
all the inkscape icon names can be found here:
http://wiki.inkscape.org/wiki/index.php/Themable_icons
=> Adds more inkscape icons

Numix/16/actions/segment-curve.svg, Numix/16/actions/segment-line.svg, Numix/22/actions/segment-curve.svg, Numix/22/actions/segment-line.svg, Numix/24/actions/segment-curve.svg, Numix/24/actions/segment-line.svg, Numix/32/actions/segment-curve.svg, Numix/32/actions/segment-line.svg, Numix/48/actions/segment-curve.svg, Numix/48/actions/segment-line.svg, Numix/64/actions/segment-curve.svg, Numix/64/actions/segment-line.svg
=> Adds segment-* icons

Numix/16/mimetypes/image-x-3ds.svg, Numix/16/mimetypes/model.svg, Numix/22/mimetypes/image-x-3ds.svg, Numix/22/mimetypes/model.svg, Numix/24/mimetypes/image-x-3ds.svg, Numix/24/mimetypes/model.svg, Numix/32/mimetypes/image-x-3ds.svg, Numix/32/mimetypes/model.svg, Numix/48/mimetypes/image-x-3ds.svg, Numix/48/mimetypes/model.svg, Numix/64/mimetypes/image-x-3ds.svg, Numix/64/mimetypes/model.svg
From #437 (only a few more icons left \o/)
=> Adds model.svg

Numix-Light/16/status/ic_dark_enpass.svg, Numix-Light/16/status/ic_light_enpass.svg, Numix-Light/22/status/ic_dark_enpass.svg, Numix-Light/22/status/ic_light_enpass.svg, Numix-Light/24/status/ic_dark_enpass.svg, Numix-Light/24/status/ic_light_enpass.svg, Numix/16/status/ic_dark_enpass.svg, Numix/16/status/ic_light_enpass.svg, Numix/22/status/ic_dark_enpass.svg, Numix/22/status/ic_light_enpass.svg, Numix/24/status/ic_dark_enpass.svg, Numix/24/status/ic_light_enpass.svg
=> Fixes #1069

Numix-Light/16/status/google-chrome-tray.svg, Numix-Light/22/status/google-chrome-tray.svg, Numix-Light/24/status/google-chrome-tray.svg, Numix/16/status/google-chrome-tray.svg, Numix/22/status/google-chrome-tray.svg, Numix/24/status/google-chrome-tray.svg
Symlinks for google-chrome. #1072
=> Fixes #1072

Numix/16/mimetypes/audio-x-scpls.svg, Numix/22/mimetypes/audio-x-scpls.svg, Numix/24/mimetypes/audio-x-scpls.svg, Numix/32/mimetypes/audio-x-scpls.svg, Numix/48/mimetypes/audio-x-scpls.svg, Numix/64/mimetypes/audio-x-scpls.svg
It's the mimetype for the [PLS file format](https://en.wikipedia.org/wiki/PLS_%28file_format%29).
Changed the symlink from the generic audio mime icon to the playlist one.
=> Updated audio-x-scpls symlink

Numix/16/mimetypes/application-x-ipynb+json.svg, Numix/16/mimetypes/text-x-ipynb.svg, Numix/22/mimetypes/application-x-ipynb+json.svg, Numix/22/mimetypes/text-x-ipynb.svg, Numix/24/mimetypes/application-x-ipynb+json.svg, Numix/24/mimetypes/text-x-ipynb.svg, Numix/32/mimetypes/application-x-ipynb+json.svg, Numix/32/mimetypes/text-x-ipynb.svg, Numix/48/mimetypes/application-x-ipynb+json.svg, Numix/48/mimetypes/text-x-ipynb.svg, Numix/64/mimetypes/application-x-ipynb+json.svg, Numix/64/mimetypes/text-x-ipynb.svg
=> Mimetype for Jupyter/IPython notebooks

Numix-Light/scalable/actions/view-app-grid-symbolic.svg, Numix/scalable/actions/view-app-grid-symbolic.svg
=> Fixes #1050

Numix/16/places/library-places.svg, Numix/22/places/library-places.svg, Numix/24/places/library-places.svg, Numix/32/places/library-places.svg, Numix/48/places/library-places.svg, Numix/64/places/library-places.svg
=> Adds library-places

Numix/16/places/library-audiobook.svg, Numix/22/places/library-audiobook.svg, Numix/24/places/library-audiobook.svg, Numix/32/places/library-audiobook.svg, Numix/48/places/library-audiobook.svg, Numix/64/places/library-audiobook.svg
=> Adds library-audiobook.svg

Numix/16/actions/xfsm-hibernate.svg, Numix/16/actions/xfsm-suspend.svg, Numix/22/actions/xfsm-hibernate.svg, Numix/22/actions/xfsm-suspend.svg, Numix/24/actions/xfsm-hibernate.svg, Numix/24/actions/xfsm-suspend.svg, Numix/32/actions/xfsm-hibernate.svg, Numix/32/actions/xfsm-suspend.svg, Numix/48/actions/xfsm-hibernate.svg, Numix/48/actions/xfsm-suspend.svg, Numix/64/actions/xfsm-hibernate.svg, Numix/64/actions/xfsm-suspend.svg
=> Fixes #1028

Numix/16/devices/i-network-printer.svg, Numix/16/devices/printer-network.svg, Numix/22/devices/i-network-printer.svg, Numix/22/devices/printer-network.svg, Numix/24/devices/i-network-printer.svg, Numix/24/devices/printer-network.svg, Numix/32/devices/i-network-printer.svg, Numix/32/devices/printer-network.svg, Numix/48/devices/i-network-printer.svg, Numix/48/devices/printer-network.svg, Numix/64/devices/i-network-printer.svg, Numix/64/devices/printer-network.svg
For the `16px` file I only used a different colour, because the "network-part" did not fit, and making it smaller only reduces recognizabilty of the whole icon
=> Fixes #1007

Numix/16/actions/stock_xfburn-burn-cd.svg, Numix/22/actions/stock_xfburn-burn-cd.svg, Numix/24/actions/stock_xfburn-burn-cd.svg, Numix/32/actions/stock_xfburn-burn-cd.svg, Numix/48/actions/stock_xfburn-burn-cd.svg, Numix/64/actions/stock_xfburn-burn-cd.svg
=> Fixes #901

Numix/16/apps/jockey.svg, Numix/22/apps/jockey.svg, Numix/24/apps/jockey.svg, Numix/32/apps/jockey.svg, Numix/48/apps/jockey.svg, Numix/64/apps/jockey.svg
=> Icon for additional driver

Numix/16/apps/jockey-proprietary.svg, Numix/16/devices/input-touchpad.svg, Numix/22/apps/jockey-proprietary.svg, Numix/22/devices/input-touchpad.svg, Numix/24/apps/jockey-proprietary.svg, Numix/24/devices/input-touchpad.svg, Numix/32/apps/jockey-proprietary.svg, Numix/32/devices/input-touchpad.svg, Numix/48/apps/jockey-proprietary.svg, Numix/48/devices/input-touchpad.svg, Numix/64/apps/jockey-proprietary.svg, Numix/64/devices/input-touchpad.svg
From #437
P.S.: There are more icons from my last few PRs that can be ticked off that list.
=> Two icons for elementary

Numix-Light/16/status/trimage-indicator.svg, Numix-Light/22/status/trimage-indicator.svg, Numix-Light/24/status/trimage-indicator.svg, Numix/16/status/trimage-indicator.svg, Numix/22/status/trimage-indicator.svg, Numix/24/status/trimage-indicator.svg
=> Adds trimage-indicator icon

Numix-Light/16/status/nm-wwan-tower.svg, Numix-Light/22/status/nm-wwan-tower.svg, Numix-Light/24/status/nm-wwan-tower.svg, Numix/16/status/nm-wwan-tower.svg, Numix/22/status/nm-wwan-tower.svg, Numix/24/status/nm-wwan-tower.svg
This should now really fix #989. There are actually 4 icons overlayed, this is extremely stupid...
=> Makes nm-wwan-tower-transparent

Numix/16/actions/system-suspend-hibernate.svg, Numix/16/actions/system-suspend.svg, Numix/22/actions/system-suspend-hibernate.svg, Numix/22/actions/system-suspend.svg, Numix/24/actions/system-suspend-hibernate.svg, Numix/24/actions/system-suspend.svg, Numix/32/actions/system-suspend-hibernate.svg, Numix/32/actions/system-suspend.svg, Numix/48/actions/system-suspend-hibernate.svg, Numix/48/actions/system-suspend.svg, Numix/64/actions/system-suspend-hibernate.svg, Numix/64/actions/system-suspend.svg
=> Adds system-hibernate/suspend symlinks

Numix-Light/16/status/blueberry-active.svg, Numix-Light/16/status/blueberry-disabled.svg, Numix-Light/16/status/blueberry.svg, Numix-Light/22/status/blueberry-active.svg, Numix-Light/22/status/blueberry-disabled.svg, Numix-Light/22/status/blueberry.svg, Numix-Light/24/status/blueberry-active.svg, Numix-Light/24/status/blueberry-disabled.svg, Numix-Light/24/status/blueberry.svg, Numix/16/status/blueberry-active.svg, Numix/16/status/blueberry-disabled.svg, Numix/16/status/blueberry.svg, Numix/22/status/blueberry-active.svg, Numix/22/status/blueberry-disabled.svg, Numix/22/status/blueberry.svg, Numix/24/status/blueberry-active.svg, Numix/24/status/blueberry-disabled.svg, Numix/24/status/blueberry.svg
=> Adds symlinks for blueberry

Numix-Light/16/status/mintupload-tray.svg, Numix-Light/22/status/mintupload-tray.svg, Numix-Light/24/status/mintupload-tray.svg, Numix/16/status/mintupload-tray.svg, Numix/22/status/mintupload-tray.svg, Numix/24/status/mintupload-tray.svg
=> Adds mintupload-tray icons

Numix-Light/16/status/nomachine-disabled.svg, Numix-Light/16/status/nomachine-indicator.svg, Numix-Light/22/status/nomachine-disabled.svg, Numix-Light/22/status/nomachine-indicator.svg, Numix-Light/24/status/nomachine-disabled.svg, Numix-Light/24/status/nomachine-indicator.svg, Numix/16/status/nomachine-disabled.svg, Numix/16/status/nomachine-indicator.svg, Numix/22/status/nomachine-disabled.svg, Numix/22/status/nomachine-indicator.svg, Numix/24/status/nomachine-disabled.svg, Numix/24/status/nomachine-indicator.svg
=> Adds nomachine icons

Numix/24/mimetypes/text-markdown.svg, Numix/48/mimetypes/text-markdown.svg
We were missing two symlinks in smaller sizes. I'll merge that right away
=> Fixes #1188

Numix-Light/16/panel/indicator-stickynotes-mono.svg, Numix-Light/22/panel/indicator-stickynotes-mono.svg, Numix-Light/24/panel/indicator-stickynotes-mono.svg, Numix/16/panel/indicator-stickynotes-mono.svg, Numix/22/panel/indicator-stickynotes-mono.svg, Numix/24/panel/indicator-stickynotes-mono.svg
=> Fixes #1237

Numix-Light/scalable/mimetypes/application-rss+xml-symbolic.svg, Numix/scalable/mimetypes/application-rss+xml-symbolic.svg
=> Fixes symbolic RSS mimetype

Numix-Light/16/status/synergy-panel-ok.svg, Numix-Light/16/status/synergy-panel.svg, Numix-Light/22/status/synergy-panel-ok.svg, Numix-Light/22/status/synergy-panel.svg, Numix-Light/24/status/synergy-panel-ok.svg, Numix-Light/24/status/synergy-panel.svg, Numix/16/status/synergy-panel-ok.svg, Numix/16/status/synergy-panel.svg, Numix/22/status/synergy-panel-ok.svg, Numix/22/status/synergy-panel.svg, Numix/24/status/synergy-panel-ok.svg, Numix/24/status/synergy-panel.svg
Tray icons for synergy, a mouse sharing app. Unfortunately hardcoded but Hardcoded-Tray fixes them
=> Adds synergy status icons

Numix-Light/scalable/status/message-indicator-symbolic.svg, Numix/scalable/status/message-indicator-symbolic.svg
Fixes #1248
Just a 4x4 circle like it looked before. Will decide what to do with ``message.svg`` later.
=> Provide message-indicator-symbolic

Numix/16/devices/drive-multidisk.svg, Numix/22/devices/drive-multidisk.svg, Numix/24/devices/drive-multidisk.svg, Numix/32/devices/drive-multidisk.svg, Numix/48/devices/drive-multidisk.svg, Numix/64/devices/drive-multidisk.svg
=> Adds drive-multidisk

Numix-Light/16/status/clipman.svg, Numix-Light/22/status/clipman.svg, Numix-Light/24/status/clipman.svg, Numix/16/status/clipman.svg, Numix/22/status/clipman.svg, Numix/24/status/clipman.svg
=> Improves design of clipman

Numix-Light/16/status/gitter-indicator-disconnected.svg, Numix-Light/16/status/gitter-indicator-notification.svg, Numix-Light/16/status/gitter-indicator.svg, Numix-Light/22/status/gitter-indicator-disconnected.svg, Numix-Light/22/status/gitter-indicator-notification.svg, Numix-Light/22/status/gitter-indicator.svg, Numix-Light/24/status/gitter-indicator-disconnected.svg, Numix-Light/24/status/gitter-indicator-notification.svg, Numix-Light/24/status/gitter-indicator.svg, Numix/16/status/gitter-indicator-disconnected.svg, Numix/16/status/gitter-indicator-notification.svg, Numix/16/status/gitter-indicator.svg, Numix/22/status/gitter-indicator-disconnected.svg, Numix/22/status/gitter-indicator-notification.svg, Numix/22/status/gitter-indicator.svg, Numix/24/status/gitter-indicator-disconnected.svg, Numix/24/status/gitter-indicator-notification.svg, Numix/24/status/gitter-indicator.svg
=> Fixes #1220

Numix/16/devices/computer-laptop.svg, Numix/16/devices/laptop.svg, Numix/22/devices/computer-laptop.svg, Numix/22/devices/laptop.svg, Numix/24/devices/computer-laptop.svg, Numix/24/devices/laptop.svg, Numix/32/devices/computer-laptop.svg, Numix/32/devices/laptop.svg, Numix/48/devices/computer-laptop.svg, Numix/48/devices/laptop.svg, Numix/64/devices/computer-laptop.svg, Numix/64/devices/laptop.svg
=> Adds laptop icons to devices

Numix-Light/16/status/update-high.svg, Numix-Light/16/status/update-low.svg, Numix-Light/16/status/update-medium.svg, Numix-Light/16/status/update-none.svg, Numix-Light/22/status/update-high.svg, Numix-Light/22/status/update-low.svg, Numix-Light/22/status/update-medium.svg, Numix-Light/22/status/update-none.svg, Numix-Light/24/status/update-high.svg, Numix-Light/24/status/update-low.svg, Numix-Light/24/status/update-medium.svg, Numix-Light/24/status/update-none.svg, Numix/16/status/update-high.svg, Numix/16/status/update-low.svg, Numix/16/status/update-medium.svg, Numix/16/status/update-none.svg, Numix/22/status/update-high.svg, Numix/22/status/update-low.svg, Numix/22/status/update-medium.svg, Numix/22/status/update-none.svg, Numix/24/status/update-high.svg, Numix/24/status/update-low.svg, Numix/24/status/update-medium.svg, Numix/24/status/update-none.svg
=> Adds update-* icons

Numix-Light/16/status/TeamViewer.svg, Numix-Light/22/status/TeamViewer.svg, Numix-Light/24/status/TeamViewer.svg, Numix/16/status/TeamViewer.svg, Numix/22/status/TeamViewer.svg, Numix/24/status/TeamViewer.svg
Teamviewer is now a native linux app (yay), and uses only one panel icon for now. Added them
=> Adds new teamviewer icons

Numix-Light/16/panel/enpass-status-dark.svg, Numix-Light/16/panel/enpass-status.svg, Numix-Light/22/panel/enpass-status-dark.svg, Numix-Light/22/panel/enpass-status.svg, Numix-Light/24/panel/enpass-status-dark.svg, Numix-Light/24/panel/enpass-status.svg, Numix/16/panel/enpass-status-dark.svg, Numix/16/panel/enpass-status.svg, Numix/22/panel/enpass-status-dark.svg, Numix/22/panel/enpass-status.svg, Numix/24/panel/enpass-status-dark.svg, Numix/24/panel/enpass-status.svg
Will this be merged into Numix-Circle, ...?
=> Add panel icons for enpass6

Numix/16/mimetypes/text-x-groovy.svg, Numix/22/mimetypes/text-x-groovy.svg, Numix/24/mimetypes/text-x-groovy.svg, Numix/32/mimetypes/text-x-groovy.svg, Numix/48/mimetypes/text-x-groovy.svg, Numix/64/mimetypes/text-x-groovy.svg
=> mimetype icons for Groovy source files

Numix/16/actions/rhythmbox-set-star.svg, Numix/22/actions/rhythmbox-set-star.svg, Numix/24/actions/rhythmbox-set-star.svg, Numix/32/actions/rhythmbox-set-star.svg, Numix/48/actions/rhythmbox-set-star.svg, Numix/64/actions/rhythmbox-set-star.svg
=> Fixed Rhythmbox rating icon

Numix/16/mimetypes/text-x-kotlin.svg, Numix/22/mimetypes/text-x-kotlin.svg, Numix/24/mimetypes/text-x-kotlin.svg, Numix/32/mimetypes/text-x-kotlin.svg, Numix/48/mimetypes/text-x-kotlin.svg, Numix/64/mimetypes/text-x-kotlin.svg
=> Mimetype icons for Kotlin source files

Numix/16/mimetypes/audio-x-soundfont.svg, Numix/22/mimetypes/audio-x-soundfont.svg, Numix/24/mimetypes/audio-x-soundfont.svg, Numix/32/mimetypes/audio-x-soundfont.svg, Numix/48/mimetypes/audio-x-soundfont.svg, Numix/64/mimetypes/audio-x-soundfont.svg
MIDI mimetype icon recoloured according to the grey/white scheme.
Fixes for some MIDI icons.
=> Sondfont mimetype icons

Numix-Light/scalable/actions/document-edit-symbolic.svg, Numix/scalable/actions/document-edit-symbolic.svg
=> symlink for document-edit-symbolic

Numix/16/mimetypes/text-x-haskell.svg, Numix/22/mimetypes/text-x-haskell.svg, Numix/24/mimetypes/text-x-haskell.svg, Numix/32/mimetypes/text-x-haskell.svg, Numix/48/mimetypes/text-x-haskell.svg, Numix/64/mimetypes/text-x-haskell.svg
=> Dedicated mimetype icons for Haskell

Numix-Light/16/panel/telegram-attention-panel.svg, Numix-Light/16/panel/telegram-mute-panel.svg, Numix-Light/16/panel/telegram-panel.svg, Numix-Light/22/panel/telegram-attention-panel.svg, Numix-Light/22/panel/telegram-mute-panel.svg, Numix-Light/22/panel/telegram-panel.svg, Numix-Light/24/panel/telegram-attention-panel.svg, Numix-Light/24/panel/telegram-mute-panel.svg, Numix-Light/24/panel/telegram-panel.svg, Numix/16/panel/telegram-attention-panel.svg, Numix/16/panel/telegram-mute-panel.svg, Numix/16/panel/telegram-panel.svg, Numix/22/panel/telegram-attention-panel.svg, Numix/22/panel/telegram-mute-panel.svg, Numix/22/panel/telegram-panel.svg, Numix/24/panel/telegram-attention-panel.svg, Numix/24/panel/telegram-mute-panel.svg, Numix/24/panel/telegram-panel.svg
currently it does not work for me, but when having these links it does.
=> fix telegram-tray icons
