Numix-Light/16x16/status/nm-device-wired.svg
Numix-Light/22x22/status/nm-device-wired.svg
Numix-Light/24x24/status/nm-device-wired.svg

Hi, I have added `nm-device-wired.svg` symlinks (relative ones) to `network-transmit-receive.svg` in `16x16/status`, `22x22/status` and `24x24/status` by copying the symlinks over from Numix to Numix-Light.

Added nm-device-wired.svg symlinks to Numix-Light. Fixes #209

---

Numix/128x128/mimetypes/text-csharp.svg
Numix/16x16/mimetypes/text-csharp.svg
Numix/22x22/mimetypes/text-csharp.svg
Numix/24x24/mimetypes/text-csharp.svg
Numix/256x256/mimetypes/text-csharp.svg
Numix/32x32/mimetypes/text-csharp.svg
Numix/48x48/mimetypes/text-csharp.svg
Numix/64x64/mimetypes/text-csharp.svg

text-csharp.svg --> text-x-csharp.svg
Don't know whether or not it's needed, I just found it in another theme.

C# symlink

---

Numix/128x128/mimetypes/application-xspf+xml.svg
Numix/16x16/mimetypes/application-xspf+xml.svg
Numix/22x22/mimetypes/application-xspf+xml.svg
Numix/24x24/mimetypes/application-xspf+xml.svg
Numix/256x256/mimetypes/application-xspf+xml.svg
Numix/32x32/mimetypes/application-xspf+xml.svg
Numix/48x48/mimetypes/application-xspf+xml.svg
Numix/64x64/mimetypes/application-xspf+xml.svg

files: .xspf are used as playlist by programs like VLC:
created a symlink **application-xspf+xml.svg** in all of available mimetype sizes

Add .xspf support

---

Numix/128x128/mimetypes/application-vnd.debian.binary-package.svg
Numix/16x16/mimetypes/application-vnd.debian.binary-package.svg
Numix/22x22/mimetypes/application-vnd.debian.binary-package.svg
Numix/24x24/mimetypes/application-vnd.debian.binary-package.svg
Numix/256x256/mimetypes/application-vnd.debian.binary-package.svg
Numix/32x32/mimetypes/application-vnd.debian.binary-package.svg
Numix/48x48/mimetypes/application-vnd.debian.binary-package.svg
Numix/64x64/mimetypes/application-vnd.debian.binary-package.svg

Outside the Debian and derivatives systems the .deb files uses a different mimetype:
mimetype: **application-vnd.debian.binary-package**
Image captured in Arch Linux

Fix .deb files

---

Numix-Light/16x16/status/ac-adapter-symbolic.svg
Numix-Light/24x24/status/ac-adapter-symbolic.svg
Numix/16x16/status/ac-adapter-symbolic.svg
Numix/24x24/status/ac-adapter-symbolic.svg

Title explains it. Scaling of status icons in 24x24 and 16x16 was wrong

Fixes wrong scaling of ac-adapter-symbolic.svg

---

Numix-Light/16x16/status/user-invisible-panel.svg
Numix-Light/24x24/status/user-invisible-panel.svg
Numix/16x16/status/user-invisible-panel.svg
Numix/24x24/status/user-invisible-panel.svg

The icons were completely invisible in 16x16/status and 24x24/status (I'm afraid there are more, Inkscape strikes again...)

Fixes truly invisible user-invisible-panel.svg in 16 and 24

---

Numix-Light/16x16/status/audio-output-none-panel.svg
Numix-Light/22x22/status/audio-output-none-panel.svg
Numix-Light/24x24/status/audio-output-none-panel.svg
Numix/16x16/status/audio-output-none-panel.svg
Numix/22x22/status/audio-output-none-panel.svg
Numix/24x24/status/audio-output-none-panel.svg

The icon `audio-output-none-panel.svg` seemed off when compared to the other audio icons (position of the speaker was different) I changed that and made it consistent with the other audio icons

Fixes inconsistent icon audio-output-none-panel.svg in 16 22 and 24

---

Numix/22x22/status/redshift-status-off.svg

Deleted "glow" in the light bulb in the new `redshift-status-off.svg` for consistency with the new `redshift-status-on.svg`. Fixes https://github.com/numixproject/numix-icon-theme/issues/382.

Deleted glow

---

Numix-Light/16x16/status/battery-000-charging.svg
Numix-Light/16x16/status/battery-000.svg
Numix-Light/22x22/status/battery-000-charging.svg
Numix-Light/22x22/status/battery-000.svg
Numix-Light/24x24/status/battery-000-charging.svg
Numix-Light/24x24/status/battery-000.svg

Added `battery-000.svg` and `battery-000-charging.svg` to Numix-Light in fixed size directories 16x16, 22x22 and 24x24 by copying them over from Numix base. Fixes https://github.com/numixproject/numix-icon-theme/issues/403.

Added battery-000.svg and battery-000-charging.svg to Numix-Light

---

Numix/128x128/mimetypes/text-x-vala.svg
Numix/16x16/mimetypes/text-x-vala.svg
Numix/22x22/mimetypes/text-x-vala.svg
Numix/24x24/mimetypes/text-x-vala.svg
Numix/256x256/mimetypes/text-x-vala.svg
Numix/32x32/mimetypes/text-x-vala.svg
Numix/48x48/mimetypes/text-x-vala.svg
Numix/64x64/mimetypes/text-x-vala.svg

Existing one was the hasbang icon used for shell scripts etc.
Now with the vala symbol from Numix Circle.

Vala mimetype enhacement

---

Numix/128x128/mimetypes/text-x-matlab.svg
Numix/128x128/mimetypes/text-x-octave.svg
Numix/16x16/mimetypes/text-x-matlab.svg
Numix/16x16/mimetypes/text-x-octave.svg
Numix/22x22/mimetypes/text-x-matlab.svg
Numix/22x22/mimetypes/text-x-octave.svg
Numix/24x24/mimetypes/text-x-matlab.svg
Numix/24x24/mimetypes/text-x-octave.svg
Numix/256x256/mimetypes/text-x-matlab.svg
Numix/256x256/mimetypes/text-x-octave.svg
Numix/32x32/mimetypes/text-x-matlab.svg
Numix/32x32/mimetypes/text-x-octave.svg
Numix/48x48/mimetypes/text-x-matlab.svg
Numix/48x48/mimetypes/text-x-octave.svg
Numix/64x64/mimetypes/text-x-matlab.svg
Numix/64x64/mimetypes/text-x-octave.svg

Pushed design, same colour as formula mimetype:
Alternative colour (from cubes in Octave logo):

Added mimetype for Octave files

---

Numix/128x128/actions/image-loading.svg
Numix/16x16/actions/image-loading.svg
Numix/22x22/actions/image-loading.svg
Numix/24x24/actions/image-loading.svg
Numix/256x256/actions/image-loading.svg
Numix/32x32/actions/image-loading.svg
Numix/48x48/actions/image-loading.svg
Numix/64x64/actions/image-loading.svg
Numix/96x96/actions/image-loading.svg

Image loading (used for preview thumbnails) icons were missing but loading icon (similar to elementary icon theme) was already present. -> Symlinks

Symlinks for image-loading.svg fixes #138

---

Numix-Light/16x16/status/network-wired.svg
Numix-Light/22x22/status/network-wired.svg
Numix-Light/24x24/status/network-wired.svg
Numix/128x128/devices/network-wired.svg
Numix/16x16/devices/network-wired.svg
Numix/16x16/status/network-wired.svg
Numix/22x22/devices/network-wired.svg
Numix/22x22/status/network-wired.svg
Numix/24x24/devices/network-wired.svg
Numix/24x24/status/network-wired.svg
Numix/256x256/devices/network-wired.svg
Numix/32x32/devices/network-wired.svg
Numix/48x48/devices/network-wired.svg
Numix/64x64/devices/network-wired.svg

As discussed in #458, removes unnecessary `network-wired.svg` in `status` and adds symlinks to `nm-device-wired.svg` in `devices`

Removes network wired from status. Adds symlinks in devices

---

Numix-Light/scalable/status/network-wired-symbolic.svg
Numix/scalable/status/network-wired-symbolic.svg

In continuation of https://github.com/numixproject/numix-icon-theme/pull/478 and https://github.com/numixproject/numix-icon-theme/pull/480, this is an enhanced version of `network-wired-symbolic.svg` for Numix and for Numix-Light.
This icon is consistent with the other "wired" icons in Numix base, and it is consistent with the other Numix icons in GNOME Shell.
Icon:
In GNOME Shell (3.16):

Enhanced network-wired-symbolic.svg

---

Numix/128x128/actions/credentials-add-account.svg
Numix/16x16/actions/credentials-add-account.svg
Numix/22x22/actions/credentials-add-account.svg
Numix/24x24/actions/credentials-add-account.svg
Numix/256x256/actions/credentials-add-account.svg
Numix/32x32/actions/credentials-add-account.svg
Numix/48x48/actions/credentials-add-account.svg
Numix/64x64/actions/credentials-add-account.svg

The last icon in Ubuntu that was not themed by Numix I was able to find. The button that adds an online-account in system settings. Symlink to `list-add.svg`

Adds credentials-add-account to actions

---

Numix-Light/16x16/status/touchpad-indicator-dark-disabled.svg
Numix-Light/16x16/status/touchpad-indicator-dark-enabled.svg
Numix-Light/16x16/status/touchpad-indicator-dark.svg
Numix-Light/16x16/status/touchpad-indicator-light-disabled.svg
Numix-Light/16x16/status/touchpad-indicator-light-enabled.svg
Numix-Light/16x16/status/touchpad-indicator-light.svg
Numix-Light/16x16/status/variety-indicator-dark.svg
Numix-Light/16x16/status/variety-indicator.svg
Numix-Light/22x22/status/touchpad-indicator-dark-disabled.svg
Numix-Light/22x22/status/touchpad-indicator-dark-enabled.svg
Numix-Light/22x22/status/touchpad-indicator-dark.svg
Numix-Light/22x22/status/touchpad-indicator-light-disabled.svg
Numix-Light/22x22/status/touchpad-indicator-light-enabled.svg
Numix-Light/22x22/status/touchpad-indicator-light.svg
Numix-Light/22x22/status/variety-indicator-dark.svg
Numix-Light/22x22/status/variety-indicator.svg
Numix-Light/24x24/status/touchpad-indicator-dark-disabled.svg
Numix-Light/24x24/status/touchpad-indicator-dark-enabled.svg
Numix-Light/24x24/status/touchpad-indicator-dark.svg
Numix-Light/24x24/status/touchpad-indicator-light-disabled.svg
Numix-Light/24x24/status/touchpad-indicator-light-enabled.svg
Numix-Light/24x24/status/touchpad-indicator-light.svg
Numix-Light/24x24/status/variety-indicator-dark.svg
Numix-Light/24x24/status/variety-indicator.svg

Please cf. conversation at https://github.com/numixproject/numix-icon-theme/pull/457.
These icons are of the same name and of the same design as in Numix base, and since Numix-Light inherits from Numix base, they are unnecessary in Numix-Light.
Such identical icons in Numix base and Numix-Light should only be included in Numix-Light if the inheritance from Numix base for some reason does not work, as e.g. for the red battery status icons.

Removed unnecessary symlinks in Numix-Light

---

Numix/16x16/devices/drive-harddisk-usb_alternative.svg
Numix/22x22/devices/drive-harddisk-usb_alternative.svg
Numix/24x24/devices/drive-harddisk-usb_alternative.svg
Numix/32x32/devices/drive-harddisk-usb_alternative.svg
Numix/48x48/devices/drive-harddisk-usb_alternative.svg

`devices` directories up to size `48x48`. Addresses https://github.com/numixproject/numix-icon-theme/issues/101, cf. comments over there.

Added usb alternative icon

---

Numix/128x128/mimetypes/text-x-pascal.svg
Numix/16x16/mimetypes/text-x-pascal.svg
Numix/22x22/mimetypes/text-x-pascal.svg
Numix/24x24/mimetypes/text-x-pascal.svg
Numix/256x256/mimetypes/text-x-pascal.svg
Numix/32x32/mimetypes/text-x-pascal.svg
Numix/48x48/mimetypes/text-x-pascal.svg
Numix/64x64/mimetypes/text-x-pascal.svg

Modified Lazarus symbol (mascot of the Free Pascal Compiler is a cheetah).
Pushed the upper line:

Mimetype for Pascal source files

---

Numix/128x128/actions/gtk-connect.svg
Numix/128x128/actions/gtk-disconnect.svg
Numix/16x16/actions/gtk-connect.svg
Numix/16x16/actions/gtk-disconnect.svg
Numix/22x22/actions/gtk-connect.svg
Numix/22x22/actions/gtk-disconnect.svg
Numix/24x24/actions/gtk-connect.svg
Numix/24x24/actions/gtk-disconnect.svg
Numix/256x256/actions/gtk-connect.svg
Numix/256x256/actions/gtk-disconnect.svg
Numix/32x32/actions/gtk-connect.svg
Numix/32x32/actions/gtk-disconnect.svg
Numix/48x48/actions/gtk-connect.svg
Numix/48x48/actions/gtk-disconnect.svg
Numix/64x64/actions/gtk-connect.svg
Numix/64x64/actions/gtk-disconnect.svg

I made an error when designing these icons. Instead of full opacity I used 90% (don't ask me why...)

Fixes opacity of gtk-connect and gtk-disconnect

---

Numix/128x128/actions/gtk-index.svg
Numix/16x16/actions/gtk-index.svg
Numix/22x22/actions/gtk-index.svg
Numix/24x24/actions/gtk-index.svg
Numix/256x256/actions/gtk-index.svg
Numix/32x32/actions/gtk-index.svg
Numix/48x48/actions/gtk-index.svg
Numix/64x64/actions/gtk-index.svg

I made an improvement for `gtk-index.svg` arguably the worst icon I commited in the last days. This is much better now. 
My proposed version for the gtk icons now:

gtk-index overhaul

---

Numix/128x128/status/aptdaemon-add.svg
Numix/16x16/status/aptdaemon-add.svg
Numix/22x22/status/aptdaemon-add.svg
Numix/24x24/status/aptdaemon-add.svg
Numix/256x256/status/aptdaemon-add.svg
Numix/32x32/status/aptdaemon-add.svg
Numix/48x48/status/aptdaemon-add.svg
Numix/64x64/status/aptdaemon-add.svg

While trying to fix #184 I recognized that none of the `aptdaemon-add.svg` icons in status is aligned to grid. I changed the icons accordingly

Aligns aptdaemon to grid

---

Numix-Light/scalable/status/network-wired-acquiring-symbolic.svg
Numix/scalable/status/network-wired-acquiring-symbolic.svg

Fixes https://github.com/numixproject/numix-icon-theme/issues/570.
The icon is designed to be in line with the already existing `network-wireless-acquiring-symbolic.svg`:

Added network-wired-acquiring-symbolic.svg

---

Numix-Light/scalable/devices/drive-harddisk-solidstate-symbolic.svg
Numix/scalable/devices/drive-harddisk-solidstate-symbolic.svg

Fixes https://github.com/numixproject/numix-icon-theme/issues/585.
The design is based on and in line with `drive-harddisk-symbolic.svg`:

Added drive-harddisk-solidstate-symbolic.svg

---

Numix/128x128/actions/nemo-eject.svg
Numix/16x16/actions/nemo-eject.svg
Numix/22x22/actions/nemo-eject.svg
Numix/24x24/actions/nemo-eject.svg
Numix/256x256/actions/nemo-eject.svg
Numix/32x32/actions/nemo-eject.svg
Numix/48x48/actions/nemo-eject.svg
Numix/64x64/actions/nemo-eject.svg

Added ``nemo-eject.svg``. It's the drive eject icon for Nemo.
Original design present in ``hicolor/16x16/actions`` and ``hicolor/32x32/actions``:
New design:
The new one however will be shown only when just the Numix base theme is chosen.
With Numix Circle selected for some reason still the app icon ``nemo.svg`` is shown (related to #132)

Added nemo-eject.svg

---

Numix/128x128/actions/document-export.svg
Numix/128x128/actions/document-import.svg
Numix/16x16/actions/document-export.svg
Numix/16x16/actions/document-import.svg
Numix/22x22/actions/document-import.svg
Numix/24x24/actions/document-export.svg
Numix/24x24/actions/document-import.svg
Numix/256x256/actions/document-export.svg
Numix/256x256/actions/document-import.svg
Numix/32x32/actions/document-export.svg
Numix/32x32/actions/document-import.svg
Numix/48x48/actions/document-export.svg
Numix/48x48/actions/document-import.svg
Numix/64x64/actions/document-export.svg
Numix/64x64/actions/document-import.svg

Added ``document-import`` (one from #437) by basically mirroring existing ``document-export``.
Fixed alignment in ``document-export``.
Exapmle (altered colour for the sake of visibility):
``document-export``
``document-import``

Added document-import action icon

---

Numix/128x128/actions/eog-image-gallery.svg
Numix/128x128/actions/image-gallery.svg
Numix/128x128/actions/slideshow-play.svg
Numix/16x16/actions/eog-image-gallery.svg
Numix/16x16/actions/image-gallery.svg
Numix/16x16/actions/slideshow-play.svg
Numix/22x22/actions/eog-image-gallery.svg
Numix/22x22/actions/image-gallery.svg
Numix/22x22/actions/slideshow-play.svg
Numix/24x24/actions/eog-image-gallery.svg
Numix/24x24/actions/image-gallery.svg
Numix/24x24/actions/slideshow-play.svg
Numix/256x256/actions/eog-image-gallery.svg
Numix/256x256/actions/image-gallery.svg
Numix/256x256/actions/slideshow-play.svg
Numix/32x32/actions/eog-image-gallery.svg
Numix/32x32/actions/image-gallery.svg
Numix/32x32/actions/slideshow-play.svg
Numix/48x48/actions/eog-image-gallery.svg
Numix/48x48/actions/image-gallery.svg
Numix/48x48/actions/slideshow-play.svg
Numix/64x64/actions/eog-image-gallery.svg
Numix/64x64/actions/image-gallery.svg
Numix/64x64/actions/slideshow-play.svg

Missing action icons for Eye of GNOME/MATE and other image viewers:
Original eog icons
``(eog)-image-gallery``
``slideshow-play``
``slideshow-play`` pushed as symlink to ``media-playback-start``.
Pushed design for ``image-gallery``:
Alternative design:

Added missing Eye of GNOME action icons

---

Numix/128x128/actions/calendar-go-today.svg
Numix/16x16/actions/calendar-go-today.svg
Numix/22x22/actions/calendar-go-today.svg
Numix/24x24/actions/calendar-go-today.svg
Numix/256x256/actions/calendar-go-today.svg
Numix/32x32/actions/calendar-go-today.svg
Numix/48x48/actions/calendar-go-today.svg
Numix/64x64/actions/calendar-go-today.svg

Action icon used by elementary's Maya calendar app.
It's not part of the ``elementary`` theme but located in ``hicolor`` by default.

Symlinks for calendar-go-today

---

Numix/128x128/mimetypes/application-mathematica.svg
Numix/16x16/mimetypes/application-mathematica.svg
Numix/22x22/mimetypes/application-mathematica.svg
Numix/24x24/mimetypes/application-mathematica.svg
Numix/256x256/mimetypes/application-mathematica.svg
Numix/32x32/mimetypes/application-mathematica.svg
Numix/48x48/mimetypes/application-mathematica.svg
Numix/64x64/mimetypes/application-mathematica.svg

The symbol from `wolfram-mathematica` in circle makes a way better mimetype icon for `application-mathematica`

Mathematica mimetype enhancement

---

Numix-Light/scalable/devices/media-removable-symbolic.svg
Numix/scalable/devices/media-removable-symbolic.svg

I used the more generic "removable" icon because it fits better for a general usb-indicator icon. #702

Symlinks for media-removable-symbolic fixes #702

---

Numix/128x128/categories/preferences-system-windows.svg
Numix/16x16/categories/preferences-system-windows.svg
Numix/22x22/categories/preferences-system-windows.svg
Numix/24x24/categories/preferences-system-windows.svg
Numix/256x256/categories/preferences-system-windows.svg
Numix/32x32/categories/preferences-system-windows.svg
Numix/48x48/categories/preferences-system-windows.svg
Numix/64x64/categories/preferences-system-windows.svg

Added a symlink to `apps/window-manager` for the smaller sizes, but I had to add files for larger sizes, because only sizes up to `48` were present

Adds symlinks/files for preferences-system-windows fixes #659

---

Numix/96x96/places/gnome-fs-loading-icon.svg

Title says it. Btw: @Foggalong You've added your latest action icons also to 96px, is this something you want?, I'm just asking because as far as I can see all the icons (except the places icons of course) in 96px are just the same icons as in 48px just multiplied by two. This makes this a bit redundant and could for example also be defined in the index.theme (same is also true for 64, 128 and 256 btw)

Fixes wrong size for image-loading in 96px

---

Numix/16/mimetypes/application-x-gettext-translation.svg
Numix/16/mimetypes/text-x-gettext-translation-template.svg
Numix/16/mimetypes/text-x-gettext-translation.svg
Numix/16/mimetypes/text-x-po.svg
Numix/22/mimetypes/application-x-gettext-translation.svg
Numix/22/mimetypes/text-x-gettext-translation-template.svg
Numix/22/mimetypes/text-x-gettext-translation.svg
Numix/22/mimetypes/text-x-po.svg
Numix/24/mimetypes/application-x-gettext-translation.svg
Numix/24/mimetypes/text-x-gettext-translation-template.svg
Numix/24/mimetypes/text-x-gettext-translation.svg
Numix/24/mimetypes/text-x-po.svg
Numix/32/mimetypes/application-x-gettext-translation.svg
Numix/32/mimetypes/text-x-gettext-translation-template.svg
Numix/32/mimetypes/text-x-gettext-translation.svg
Numix/32/mimetypes/text-x-po.svg
Numix/48/mimetypes/application-x-gettext-translation.svg
Numix/48/mimetypes/text-x-gettext-translation-template.svg
Numix/48/mimetypes/text-x-gettext-translation.svg
Numix/48/mimetypes/text-x-po.svg
Numix/64/mimetypes/application-x-gettext-translation.svg
Numix/64/mimetypes/text-x-gettext-translation-template.svg
Numix/64/mimetypes/text-x-gettext-translation.svg
Numix/64/mimetypes/text-x-po.svg

Fixes #563 
``text-x-po`` from #580 
Additional mimetypes for ``.pot`` and ``.mo`` files (recoloured ``application-octet-stream``).
Edited the 64px ``application-octet-stream`` icon which was simply scaled up from 32px and hence less detailed than the 48px one.

Added gettext translation mimetype icons.

---

Numix/16/mimetypes/text-rust.svg
Numix/22/mimetypes/text-rust.svg
Numix/24/mimetypes/text-rust.svg
Numix/32/mimetypes/text-rust.svg
Numix/48/mimetypes/text-rust.svg
Numix/64/mimetypes/text-rust.svg

Mimetype icon for Rust source files

---

Numix/16/mimetypes/application-vnd.coffeescript.svg
Numix/22/mimetypes/application-vnd.coffeescript.svg
Numix/24/mimetypes/application-vnd.coffeescript.svg
Numix/32/mimetypes/application-vnd.coffeescript.svg
Numix/48/mimetypes/application-vnd.coffeescript.svg
Numix/64/mimetypes/application-vnd.coffeescript.svg

Quite minimalistic design this time, in line with the JS mimetype.

Mimetype icons for CoffeeScript files

---

Numix/16/mimetypes/text-x-gtkrc.svg
Numix/22/mimetypes/text-x-gtkrc.svg
Numix/24/mimetypes/text-x-gtkrc.svg
Numix/32/mimetypes/text-x-gtkrc.svg
Numix/48/mimetypes/text-x-gtkrc.svg
Numix/64/mimetypes/text-x-gtkrc.svg

The old design was irrecognisable for sizes other than 48px.

Redesign for gtkrc mimetype icons

---

Numix-Light/16/status/museeq-offline.svg
Numix-Light/16/status/museeq-panel.svg
Numix-Light/22/status/museeq-offline.svg
Numix-Light/22/status/museeq-panel.svg
Numix-Light/24/status/museeq-offline.svg
Numix-Light/24/status/museeq-panel.svg
Numix/16/status/museeq-offline.svg
Numix/16/status/museeq-panel.svg
Numix/22/status/museeq-offline.svg
Numix/22/status/museeq-panel.svg
Numix/24/status/museeq-offline.svg
Numix/24/status/museeq-panel.svg

#888. @pavethem You probably have to use https://github.com/bil-elmoussaoui/Hardcode-Tray in order to get them to show up... Some developers unfortunately decide to hardcode their icons :(

Adds museeq panel icons, fixes #888

---

Numix/16/actions/shotwell-16.svg
Numix/16/actions/shotwell-auto-enhance.svg
Numix/22/actions/shotwell-auto-enhance.svg
Numix/24/actions/shotwell-24.svg
Numix/24/actions/shotwell-auto-enhance.svg
Numix/32/actions/shotwell-auto-enhance.svg
Numix/48/actions/shotwell-auto-enhance.svg
Numix/64/actions/shotwell-auto-enhance.svg

Regrettably most of Shotwell's action icons are hardcoded.
The two icons with size suffix are only present for those particular sizes.

Shotwell action icons

---

Numix-Light/16/status/user.svg
Numix-Light/22/status/user.svg
Numix-Light/24/status/user.svg
Numix/16/status/user.svg
Numix/22/status/user.svg
Numix/24/status/user.svg

Fixes #927. This bug is related to #190. The icon `user.svg` in Numix-light caused problems because when a gtk application requests an icon that starts with `user` like `user-trash.svg` for example this icon is used instead of going down the inheritance line. 
Fortunately this icon does not need to be monochrome (because it's not a tray icon) so I changed it's color and only kept it in numix base, where it causes no problems

Fixes #972

---

Numix-Light/16/panel/remmina-panel.svg
Numix-Light/22/panel/remmina-panel.svg
Numix-Light/24/panel/remmina-panel.svg
Numix/16/panel/remmina-panel.svg
Numix/22/panel/remmina-panel.svg
Numix/24/panel/remmina-panel.svg

Remmina now allows seperate theming of their tray icons: https://github.com/FreeRDP/Remmina/pull/894
A symlink to disper-panel should be spot-on
EDIT: Revisited the icon and added a unique icon (if someone has disper and remmina installed a symlink might be a bad idea). I've added something close to the "official" remmina icon http://www.remmina.org/wp/

Adds symlink for remmina-panel

---

Numix/48/notifications/notification-microphone-sensitivity-high-symbolic.svg
Numix/48/notifications/notification-microphone-sensitivity-low-symbolic.svg
Numix/48/notifications/notification-microphone-sensitivity-medium-symbolic.svg
Numix/48/notifications/notification-microphone-sensitivity-muted-symbolic.svg

Figured out why the `symbolic` icon was shown after digging around in the source code for #1233 . The naming of the icons is super inconsistent (no idea why), so the microphone looks for `-symbolic` icons, and therefore uses the one from scalable. Adding them to `notifications` fixes it. 
Testing that can be done with `xte 'key XF86AudioMicMute'` even if no microphone is installed

Adds microphone-symbolic to notifications

---

Numix-Light/scalable/actions/view-sidebar-symbolic.svg
Numix/scalable/actions/view-sidebar-symbolic.svg

Previously this was the same as open-menu-symbolic,
which was confusing in places like evince's toolbar,
where both icons existed.

Make view-sidebar-symbolic unique

---

Numix-Light/16/panel/insync-paused.svg
Numix-Light/16/panel/insync-syncing.svg
Numix-Light/22/panel/insync-paused.svg
Numix-Light/22/panel/insync-syncing.svg
Numix-Light/24/panel/insync-paused.svg
Numix-Light/24/panel/insync-syncing.svg
Numix/16/panel/insync-paused.svg
Numix/16/panel/insync-syncing.svg
Numix/22/panel/insync-paused.svg
Numix/22/panel/insync-syncing.svg
Numix/24/panel/insync-paused.svg
Numix/24/panel/insync-syncing.svg

There is no syncing icon rotation anymore, but it switches between `insync-share` and `insync-syncing` and since `insync-syncing-2` is the least similar to other icons i used this for now.

Add missing panel icons for insync 1.5
